# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/marco/Desktop/ALU_sys_HDL_BD/ALU_sys_HDL_BD.srcs/sources_1/bd/ALU_sys_HDL_BD/ip/ALU_sys_HDL_BD_rst_ps7_0_100M_0/ALU_sys_HDL_BD_rst_ps7_0_100M_0.xci
# IP: The module: 'ALU_sys_HDL_BD_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marco/Desktop/ALU_sys_HDL_BD/ALU_sys_HDL_BD.gen/sources_1/bd/ALU_sys_HDL_BD/ip/ALU_sys_HDL_BD_rst_ps7_0_100M_0/ALU_sys_HDL_BD_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ALU_sys_HDL_BD_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marco/Desktop/ALU_sys_HDL_BD/ALU_sys_HDL_BD.gen/sources_1/bd/ALU_sys_HDL_BD/ip/ALU_sys_HDL_BD_rst_ps7_0_100M_0/ALU_sys_HDL_BD_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ALU_sys_HDL_BD_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marco/Desktop/ALU_sys_HDL_BD/ALU_sys_HDL_BD.gen/sources_1/bd/ALU_sys_HDL_BD/ip/ALU_sys_HDL_BD_rst_ps7_0_100M_0/ALU_sys_HDL_BD_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ALU_sys_HDL_BD_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/marco/Desktop/ALU_sys_HDL_BD/ALU_sys_HDL_BD.srcs/sources_1/bd/ALU_sys_HDL_BD/ip/ALU_sys_HDL_BD_rst_ps7_0_100M_0/ALU_sys_HDL_BD_rst_ps7_0_100M_0.xci
# IP: The module: 'ALU_sys_HDL_BD_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marco/Desktop/ALU_sys_HDL_BD/ALU_sys_HDL_BD.gen/sources_1/bd/ALU_sys_HDL_BD/ip/ALU_sys_HDL_BD_rst_ps7_0_100M_0/ALU_sys_HDL_BD_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ALU_sys_HDL_BD_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marco/Desktop/ALU_sys_HDL_BD/ALU_sys_HDL_BD.gen/sources_1/bd/ALU_sys_HDL_BD/ip/ALU_sys_HDL_BD_rst_ps7_0_100M_0/ALU_sys_HDL_BD_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ALU_sys_HDL_BD_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marco/Desktop/ALU_sys_HDL_BD/ALU_sys_HDL_BD.gen/sources_1/bd/ALU_sys_HDL_BD/ip/ALU_sys_HDL_BD_rst_ps7_0_100M_0/ALU_sys_HDL_BD_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ALU_sys_HDL_BD_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
