// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dec_MIMD_dec_MIMD_Pipeline_VITIS_LOOP_49_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_result_address0,
        data_result_ce0,
        data_result_we0,
        data_result_d0,
        data_a_address0,
        data_a_ce0,
        data_a_q0,
        ALU_operation_address0,
        ALU_operation_ce0,
        ALU_operation_q0,
        data_b_address0,
        data_b_ce0,
        data_b_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] data_result_address0;
output   data_result_ce0;
output   data_result_we0;
output  [31:0] data_result_d0;
output  [5:0] data_a_address0;
output   data_a_ce0;
input  [31:0] data_a_q0;
output  [5:0] ALU_operation_address0;
output   ALU_operation_ce0;
input  [31:0] ALU_operation_q0;
output  [5:0] data_b_address0;
output   data_b_ce0;
input  [31:0] data_b_q0;

reg ap_idle;
reg data_result_ce0;
reg data_result_we0;
reg[31:0] data_result_d0;
reg[5:0] data_a_address0;
reg data_a_ce0;
reg ALU_operation_ce0;
reg[5:0] data_b_address0;
reg data_b_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln49_fu_232_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] reg_214;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] ALU_operation_load_reg_441;
reg   [31:0] reg_214_pp0_iter3_reg;
reg   [31:0] reg_214_pp0_iter4_reg;
reg   [31:0] reg_214_pp0_iter5_reg;
reg   [31:0] reg_214_pp0_iter6_reg;
reg   [31:0] reg_214_pp0_iter7_reg;
reg   [31:0] reg_214_pp0_iter8_reg;
reg   [31:0] reg_214_pp0_iter9_reg;
reg   [31:0] reg_214_pp0_iter10_reg;
reg   [31:0] reg_214_pp0_iter11_reg;
reg   [31:0] reg_214_pp0_iter12_reg;
reg   [31:0] reg_214_pp0_iter13_reg;
reg   [31:0] reg_214_pp0_iter14_reg;
reg   [31:0] reg_214_pp0_iter15_reg;
reg   [31:0] reg_214_pp0_iter16_reg;
reg   [31:0] reg_214_pp0_iter17_reg;
reg   [31:0] reg_214_pp0_iter18_reg;
reg   [31:0] reg_214_pp0_iter19_reg;
reg   [31:0] reg_214_pp0_iter20_reg;
reg   [31:0] reg_214_pp0_iter21_reg;
reg   [31:0] reg_214_pp0_iter22_reg;
reg   [31:0] reg_214_pp0_iter23_reg;
reg   [31:0] reg_214_pp0_iter24_reg;
reg   [31:0] reg_214_pp0_iter25_reg;
reg   [31:0] reg_214_pp0_iter26_reg;
reg   [31:0] reg_214_pp0_iter27_reg;
reg   [31:0] reg_214_pp0_iter28_reg;
reg   [31:0] reg_214_pp0_iter29_reg;
reg   [31:0] reg_214_pp0_iter30_reg;
reg   [31:0] reg_214_pp0_iter31_reg;
reg   [31:0] reg_214_pp0_iter32_reg;
reg   [31:0] reg_214_pp0_iter33_reg;
reg   [31:0] reg_214_pp0_iter34_reg;
reg   [31:0] reg_214_pp0_iter35_reg;
reg   [31:0] reg_214_pp0_iter36_reg;
reg   [31:0] reg_214_pp0_iter37_reg;
reg   [31:0] reg_214_pp0_iter38_reg;
reg   [31:0] reg_219;
reg   [31:0] reg_219_pp0_iter3_reg;
reg   [31:0] reg_219_pp0_iter4_reg;
reg   [31:0] reg_219_pp0_iter5_reg;
reg   [31:0] reg_219_pp0_iter6_reg;
reg   [31:0] reg_219_pp0_iter7_reg;
reg   [31:0] reg_219_pp0_iter8_reg;
reg   [31:0] reg_219_pp0_iter9_reg;
reg   [31:0] reg_219_pp0_iter10_reg;
reg   [31:0] reg_219_pp0_iter11_reg;
reg   [31:0] reg_219_pp0_iter12_reg;
reg   [31:0] reg_219_pp0_iter13_reg;
reg   [31:0] reg_219_pp0_iter14_reg;
reg   [31:0] reg_219_pp0_iter15_reg;
reg   [31:0] reg_219_pp0_iter16_reg;
reg   [31:0] reg_219_pp0_iter17_reg;
reg   [31:0] reg_219_pp0_iter18_reg;
reg   [31:0] reg_219_pp0_iter19_reg;
reg   [31:0] reg_219_pp0_iter20_reg;
reg   [31:0] reg_219_pp0_iter21_reg;
reg   [31:0] reg_219_pp0_iter22_reg;
reg   [31:0] reg_219_pp0_iter23_reg;
reg   [31:0] reg_219_pp0_iter24_reg;
reg   [31:0] reg_219_pp0_iter25_reg;
reg   [31:0] reg_219_pp0_iter26_reg;
reg   [31:0] reg_219_pp0_iter27_reg;
reg   [31:0] reg_219_pp0_iter28_reg;
reg   [31:0] reg_219_pp0_iter29_reg;
reg   [31:0] reg_219_pp0_iter30_reg;
reg   [31:0] reg_219_pp0_iter31_reg;
reg   [31:0] reg_219_pp0_iter32_reg;
reg   [31:0] reg_219_pp0_iter33_reg;
reg   [31:0] reg_219_pp0_iter34_reg;
reg   [31:0] reg_219_pp0_iter35_reg;
reg   [31:0] reg_219_pp0_iter36_reg;
reg   [31:0] reg_219_pp0_iter37_reg;
reg   [31:0] reg_219_pp0_iter38_reg;
wire   [63:0] zext_ln49_fu_244_p1;
reg   [63:0] zext_ln49_reg_417;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter2_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter3_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter4_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter5_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter6_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter7_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter8_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter9_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter10_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter11_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter12_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter13_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter14_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter15_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter16_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter17_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter18_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter19_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter20_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter21_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter22_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter23_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter24_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter25_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter26_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter27_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter28_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter29_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter30_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter31_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter32_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter33_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter34_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter35_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter36_reg;
reg   [31:0] ALU_operation_load_reg_441_pp0_iter37_reg;
reg   [5:0] data_result_addr_reg_445;
reg   [5:0] data_result_addr_reg_445_pp0_iter2_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter3_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter4_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter5_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter6_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter7_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter8_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter9_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter10_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter11_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter12_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter13_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter14_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter15_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter16_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter17_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter18_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter19_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter20_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter21_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter22_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter23_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter24_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter25_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter26_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter27_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter28_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter29_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter30_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter31_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter32_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter33_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter34_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter35_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter36_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter37_reg;
reg   [5:0] data_result_addr_reg_445_pp0_iter38_reg;
wire   [5:0] data_a_addr_5_gep_fu_108_p3;
wire   [5:0] data_b_addr_5_gep_fu_116_p3;
wire   [5:0] data_a_addr_4_gep_fu_124_p3;
wire   [5:0] data_b_addr_4_gep_fu_132_p3;
wire   [5:0] data_a_addr_3_gep_fu_140_p3;
wire   [5:0] data_b_addr_3_gep_fu_148_p3;
wire   [5:0] data_b_addr_2_gep_fu_156_p3;
wire   [5:0] data_a_addr_2_gep_fu_164_p3;
wire   [5:0] data_b_addr_1_gep_fu_172_p3;
wire   [5:0] data_a_addr_1_gep_fu_180_p3;
wire   [5:0] data_b_addr_gep_fu_188_p3;
wire   [5:0] data_a_addr_gep_fu_196_p3;
wire   [31:0] sub_ln84_fu_254_p2;
reg   [31:0] sub_ln84_reg_520;
reg   [31:0] sub_ln84_reg_520_pp0_iter3_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter4_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter5_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter6_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter7_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter8_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter9_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter10_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter11_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter12_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter13_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter14_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter15_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter16_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter17_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter18_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter19_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter20_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter21_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter22_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter23_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter24_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter25_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter26_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter27_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter28_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter29_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter30_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter31_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter32_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter33_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter34_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter35_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter36_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter37_reg;
reg   [31:0] sub_ln84_reg_520_pp0_iter38_reg;
wire   [31:0] add_ln80_fu_260_p2;
reg   [31:0] add_ln80_reg_525;
reg   [31:0] add_ln80_reg_525_pp0_iter3_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter4_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter5_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter6_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter7_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter8_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter9_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter10_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter11_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter12_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter13_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter14_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter15_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter16_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter17_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter18_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter19_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter20_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter21_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter22_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter23_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter24_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter25_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter26_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter27_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter28_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter29_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter30_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter31_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter32_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter33_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter34_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter35_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter36_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter37_reg;
reg   [31:0] add_ln80_reg_525_pp0_iter38_reg;
reg   [0:0] tmp_1_reg_530;
reg   [30:0] lshr_ln76_1_reg_535;
reg   [30:0] lshr_ln76_2_reg_540;
reg   [0:0] tmp_reg_545;
reg   [30:0] lshr_ln72_1_reg_550;
reg   [30:0] lshr_ln72_2_reg_555;
wire   [31:0] select_ln76_fu_352_p3;
reg   [31:0] select_ln76_reg_560;
reg   [31:0] select_ln76_reg_560_pp0_iter4_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter5_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter6_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter7_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter8_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter9_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter10_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter11_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter12_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter13_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter14_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter15_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter16_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter17_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter18_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter19_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter20_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter21_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter22_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter23_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter24_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter25_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter26_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter27_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter28_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter29_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter30_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter31_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter32_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter33_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter34_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter35_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter36_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter37_reg;
reg   [31:0] select_ln76_reg_560_pp0_iter38_reg;
wire   [31:0] select_ln72_fu_371_p3;
reg   [31:0] select_ln72_reg_565;
reg   [31:0] select_ln72_reg_565_pp0_iter4_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter5_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter6_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter7_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter8_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter9_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter10_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter11_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter12_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter13_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter14_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter15_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter16_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter17_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter18_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter19_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter20_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter21_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter22_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter23_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter24_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter25_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter26_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter27_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter28_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter29_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter30_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter31_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter32_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter33_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter34_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter35_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter36_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter37_reg;
reg   [31:0] select_ln72_reg_565_pp0_iter38_reg;
wire   [31:0] grp_fu_210_p2;
reg   [31:0] mul_ln88_reg_570;
reg   [31:0] mul_ln88_reg_570_pp0_iter5_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter6_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter7_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter8_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter9_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter10_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter11_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter12_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter13_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter14_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter15_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter16_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter17_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter18_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter19_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter20_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter21_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter22_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter23_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter24_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter25_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter26_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter27_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter28_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter29_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter30_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter31_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter32_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter33_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter34_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter35_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter36_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter37_reg;
reg   [31:0] mul_ln88_reg_570_pp0_iter38_reg;
wire   [31:0] grp_fu_334_p2;
reg   [31:0] sdiv_ln92_reg_575;
wire    ap_block_pp0_stage0;
reg   [5:0] i_fu_58;
wire   [5:0] add_ln49_fu_238_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_2;
reg    ap_predicate_pred712_state40;
reg    ap_predicate_pred718_state40;
reg    ap_predicate_pred725_state40;
reg    ap_predicate_pred732_state40;
reg    ap_predicate_pred739_state40;
reg    ap_predicate_pred746_state40;
reg    ap_predicate_pred753_state40;
wire   [31:0] shl_ln68_fu_378_p2;
reg    ap_predicate_pred761_state40;
wire   [31:0] shl_ln64_fu_385_p2;
reg    ap_predicate_pred769_state40;
wire   [31:0] add_ln60_fu_392_p2;
reg    ap_predicate_pred777_state40;
wire   [31:0] add_ln56_fu_399_p2;
reg    ap_predicate_pred803_state40;
wire   [31:0] sub_ln76_fu_274_p2;
wire   [31:0] sub_ln72_fu_308_p2;
wire   [31:0] zext_ln76_fu_340_p1;
wire   [31:0] sub_ln76_1_fu_343_p2;
wire   [31:0] zext_ln76_1_fu_349_p1;
wire   [31:0] zext_ln72_fu_359_p1;
wire   [31:0] sub_ln72_1_fu_362_p2;
wire   [31:0] zext_ln72_1_fu_368_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_652;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 i_fu_58 = 6'd0;
#0 ap_done_reg = 1'b0;
end

dec_MIMD_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_219),
    .din1(reg_214),
    .ce(1'b1),
    .dout(grp_fu_210_p2)
);

dec_MIMD_sdiv_32ns_32ns_32_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_214),
    .din1(reg_219),
    .ce(1'b1),
    .dout(grp_fu_334_p2)
);

dec_MIMD_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter38_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln49_fu_232_p2 == 1'd0))) begin
            i_fu_58 <= add_ln49_fu_238_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_58 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ALU_operation_load_reg_441 <= ALU_operation_q0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        data_result_addr_reg_445 <= zext_ln49_reg_417;
        zext_ln49_reg_417[5 : 0] <= zext_ln49_fu_244_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ALU_operation_load_reg_441_pp0_iter10_reg <= ALU_operation_load_reg_441_pp0_iter9_reg;
        ALU_operation_load_reg_441_pp0_iter11_reg <= ALU_operation_load_reg_441_pp0_iter10_reg;
        ALU_operation_load_reg_441_pp0_iter12_reg <= ALU_operation_load_reg_441_pp0_iter11_reg;
        ALU_operation_load_reg_441_pp0_iter13_reg <= ALU_operation_load_reg_441_pp0_iter12_reg;
        ALU_operation_load_reg_441_pp0_iter14_reg <= ALU_operation_load_reg_441_pp0_iter13_reg;
        ALU_operation_load_reg_441_pp0_iter15_reg <= ALU_operation_load_reg_441_pp0_iter14_reg;
        ALU_operation_load_reg_441_pp0_iter16_reg <= ALU_operation_load_reg_441_pp0_iter15_reg;
        ALU_operation_load_reg_441_pp0_iter17_reg <= ALU_operation_load_reg_441_pp0_iter16_reg;
        ALU_operation_load_reg_441_pp0_iter18_reg <= ALU_operation_load_reg_441_pp0_iter17_reg;
        ALU_operation_load_reg_441_pp0_iter19_reg <= ALU_operation_load_reg_441_pp0_iter18_reg;
        ALU_operation_load_reg_441_pp0_iter20_reg <= ALU_operation_load_reg_441_pp0_iter19_reg;
        ALU_operation_load_reg_441_pp0_iter21_reg <= ALU_operation_load_reg_441_pp0_iter20_reg;
        ALU_operation_load_reg_441_pp0_iter22_reg <= ALU_operation_load_reg_441_pp0_iter21_reg;
        ALU_operation_load_reg_441_pp0_iter23_reg <= ALU_operation_load_reg_441_pp0_iter22_reg;
        ALU_operation_load_reg_441_pp0_iter24_reg <= ALU_operation_load_reg_441_pp0_iter23_reg;
        ALU_operation_load_reg_441_pp0_iter25_reg <= ALU_operation_load_reg_441_pp0_iter24_reg;
        ALU_operation_load_reg_441_pp0_iter26_reg <= ALU_operation_load_reg_441_pp0_iter25_reg;
        ALU_operation_load_reg_441_pp0_iter27_reg <= ALU_operation_load_reg_441_pp0_iter26_reg;
        ALU_operation_load_reg_441_pp0_iter28_reg <= ALU_operation_load_reg_441_pp0_iter27_reg;
        ALU_operation_load_reg_441_pp0_iter29_reg <= ALU_operation_load_reg_441_pp0_iter28_reg;
        ALU_operation_load_reg_441_pp0_iter2_reg <= ALU_operation_load_reg_441;
        ALU_operation_load_reg_441_pp0_iter30_reg <= ALU_operation_load_reg_441_pp0_iter29_reg;
        ALU_operation_load_reg_441_pp0_iter31_reg <= ALU_operation_load_reg_441_pp0_iter30_reg;
        ALU_operation_load_reg_441_pp0_iter32_reg <= ALU_operation_load_reg_441_pp0_iter31_reg;
        ALU_operation_load_reg_441_pp0_iter33_reg <= ALU_operation_load_reg_441_pp0_iter32_reg;
        ALU_operation_load_reg_441_pp0_iter34_reg <= ALU_operation_load_reg_441_pp0_iter33_reg;
        ALU_operation_load_reg_441_pp0_iter35_reg <= ALU_operation_load_reg_441_pp0_iter34_reg;
        ALU_operation_load_reg_441_pp0_iter36_reg <= ALU_operation_load_reg_441_pp0_iter35_reg;
        ALU_operation_load_reg_441_pp0_iter37_reg <= ALU_operation_load_reg_441_pp0_iter36_reg;
        ALU_operation_load_reg_441_pp0_iter3_reg <= ALU_operation_load_reg_441_pp0_iter2_reg;
        ALU_operation_load_reg_441_pp0_iter4_reg <= ALU_operation_load_reg_441_pp0_iter3_reg;
        ALU_operation_load_reg_441_pp0_iter5_reg <= ALU_operation_load_reg_441_pp0_iter4_reg;
        ALU_operation_load_reg_441_pp0_iter6_reg <= ALU_operation_load_reg_441_pp0_iter5_reg;
        ALU_operation_load_reg_441_pp0_iter7_reg <= ALU_operation_load_reg_441_pp0_iter6_reg;
        ALU_operation_load_reg_441_pp0_iter8_reg <= ALU_operation_load_reg_441_pp0_iter7_reg;
        ALU_operation_load_reg_441_pp0_iter9_reg <= ALU_operation_load_reg_441_pp0_iter8_reg;
        add_ln80_reg_525 <= add_ln80_fu_260_p2;
        add_ln80_reg_525_pp0_iter10_reg <= add_ln80_reg_525_pp0_iter9_reg;
        add_ln80_reg_525_pp0_iter11_reg <= add_ln80_reg_525_pp0_iter10_reg;
        add_ln80_reg_525_pp0_iter12_reg <= add_ln80_reg_525_pp0_iter11_reg;
        add_ln80_reg_525_pp0_iter13_reg <= add_ln80_reg_525_pp0_iter12_reg;
        add_ln80_reg_525_pp0_iter14_reg <= add_ln80_reg_525_pp0_iter13_reg;
        add_ln80_reg_525_pp0_iter15_reg <= add_ln80_reg_525_pp0_iter14_reg;
        add_ln80_reg_525_pp0_iter16_reg <= add_ln80_reg_525_pp0_iter15_reg;
        add_ln80_reg_525_pp0_iter17_reg <= add_ln80_reg_525_pp0_iter16_reg;
        add_ln80_reg_525_pp0_iter18_reg <= add_ln80_reg_525_pp0_iter17_reg;
        add_ln80_reg_525_pp0_iter19_reg <= add_ln80_reg_525_pp0_iter18_reg;
        add_ln80_reg_525_pp0_iter20_reg <= add_ln80_reg_525_pp0_iter19_reg;
        add_ln80_reg_525_pp0_iter21_reg <= add_ln80_reg_525_pp0_iter20_reg;
        add_ln80_reg_525_pp0_iter22_reg <= add_ln80_reg_525_pp0_iter21_reg;
        add_ln80_reg_525_pp0_iter23_reg <= add_ln80_reg_525_pp0_iter22_reg;
        add_ln80_reg_525_pp0_iter24_reg <= add_ln80_reg_525_pp0_iter23_reg;
        add_ln80_reg_525_pp0_iter25_reg <= add_ln80_reg_525_pp0_iter24_reg;
        add_ln80_reg_525_pp0_iter26_reg <= add_ln80_reg_525_pp0_iter25_reg;
        add_ln80_reg_525_pp0_iter27_reg <= add_ln80_reg_525_pp0_iter26_reg;
        add_ln80_reg_525_pp0_iter28_reg <= add_ln80_reg_525_pp0_iter27_reg;
        add_ln80_reg_525_pp0_iter29_reg <= add_ln80_reg_525_pp0_iter28_reg;
        add_ln80_reg_525_pp0_iter30_reg <= add_ln80_reg_525_pp0_iter29_reg;
        add_ln80_reg_525_pp0_iter31_reg <= add_ln80_reg_525_pp0_iter30_reg;
        add_ln80_reg_525_pp0_iter32_reg <= add_ln80_reg_525_pp0_iter31_reg;
        add_ln80_reg_525_pp0_iter33_reg <= add_ln80_reg_525_pp0_iter32_reg;
        add_ln80_reg_525_pp0_iter34_reg <= add_ln80_reg_525_pp0_iter33_reg;
        add_ln80_reg_525_pp0_iter35_reg <= add_ln80_reg_525_pp0_iter34_reg;
        add_ln80_reg_525_pp0_iter36_reg <= add_ln80_reg_525_pp0_iter35_reg;
        add_ln80_reg_525_pp0_iter37_reg <= add_ln80_reg_525_pp0_iter36_reg;
        add_ln80_reg_525_pp0_iter38_reg <= add_ln80_reg_525_pp0_iter37_reg;
        add_ln80_reg_525_pp0_iter3_reg <= add_ln80_reg_525;
        add_ln80_reg_525_pp0_iter4_reg <= add_ln80_reg_525_pp0_iter3_reg;
        add_ln80_reg_525_pp0_iter5_reg <= add_ln80_reg_525_pp0_iter4_reg;
        add_ln80_reg_525_pp0_iter6_reg <= add_ln80_reg_525_pp0_iter5_reg;
        add_ln80_reg_525_pp0_iter7_reg <= add_ln80_reg_525_pp0_iter6_reg;
        add_ln80_reg_525_pp0_iter8_reg <= add_ln80_reg_525_pp0_iter7_reg;
        add_ln80_reg_525_pp0_iter9_reg <= add_ln80_reg_525_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        ap_predicate_pred712_state40 <= (32'd9 == ALU_operation_load_reg_441_pp0_iter37_reg);
        ap_predicate_pred718_state40 <= (32'd8 == ALU_operation_load_reg_441_pp0_iter37_reg);
        ap_predicate_pred725_state40 <= (32'd7 == ALU_operation_load_reg_441_pp0_iter37_reg);
        ap_predicate_pred732_state40 <= (32'd6 == ALU_operation_load_reg_441_pp0_iter37_reg);
        ap_predicate_pred739_state40 <= (32'd5 == ALU_operation_load_reg_441_pp0_iter37_reg);
        ap_predicate_pred746_state40 <= (32'd4 == ALU_operation_load_reg_441_pp0_iter37_reg);
        ap_predicate_pred753_state40 <= (32'd3 == ALU_operation_load_reg_441_pp0_iter37_reg);
        ap_predicate_pred761_state40 <= (32'd2 == ALU_operation_load_reg_441_pp0_iter37_reg);
        ap_predicate_pred769_state40 <= (32'd1 == ALU_operation_load_reg_441_pp0_iter37_reg);
        ap_predicate_pred777_state40 <= (32'd0 == ALU_operation_load_reg_441_pp0_iter37_reg);
        ap_predicate_pred803_state40 <= (~(32'd0 == ALU_operation_load_reg_441_pp0_iter37_reg) & ~(32'd1 == ALU_operation_load_reg_441_pp0_iter37_reg) & ~(32'd2 == ALU_operation_load_reg_441_pp0_iter37_reg) & ~(32'd3 == ALU_operation_load_reg_441_pp0_iter37_reg) & ~(32'd4 == ALU_operation_load_reg_441_pp0_iter37_reg) & ~(32'd5 == ALU_operation_load_reg_441_pp0_iter37_reg) & ~(32'd6 == ALU_operation_load_reg_441_pp0_iter37_reg) & ~(32'd7 == ALU_operation_load_reg_441_pp0_iter37_reg) & ~(32'd8 == ALU_operation_load_reg_441_pp0_iter37_reg) & ~(32'd9 == ALU_operation_load_reg_441_pp0_iter37_reg));
        data_result_addr_reg_445_pp0_iter10_reg <= data_result_addr_reg_445_pp0_iter9_reg;
        data_result_addr_reg_445_pp0_iter11_reg <= data_result_addr_reg_445_pp0_iter10_reg;
        data_result_addr_reg_445_pp0_iter12_reg <= data_result_addr_reg_445_pp0_iter11_reg;
        data_result_addr_reg_445_pp0_iter13_reg <= data_result_addr_reg_445_pp0_iter12_reg;
        data_result_addr_reg_445_pp0_iter14_reg <= data_result_addr_reg_445_pp0_iter13_reg;
        data_result_addr_reg_445_pp0_iter15_reg <= data_result_addr_reg_445_pp0_iter14_reg;
        data_result_addr_reg_445_pp0_iter16_reg <= data_result_addr_reg_445_pp0_iter15_reg;
        data_result_addr_reg_445_pp0_iter17_reg <= data_result_addr_reg_445_pp0_iter16_reg;
        data_result_addr_reg_445_pp0_iter18_reg <= data_result_addr_reg_445_pp0_iter17_reg;
        data_result_addr_reg_445_pp0_iter19_reg <= data_result_addr_reg_445_pp0_iter18_reg;
        data_result_addr_reg_445_pp0_iter20_reg <= data_result_addr_reg_445_pp0_iter19_reg;
        data_result_addr_reg_445_pp0_iter21_reg <= data_result_addr_reg_445_pp0_iter20_reg;
        data_result_addr_reg_445_pp0_iter22_reg <= data_result_addr_reg_445_pp0_iter21_reg;
        data_result_addr_reg_445_pp0_iter23_reg <= data_result_addr_reg_445_pp0_iter22_reg;
        data_result_addr_reg_445_pp0_iter24_reg <= data_result_addr_reg_445_pp0_iter23_reg;
        data_result_addr_reg_445_pp0_iter25_reg <= data_result_addr_reg_445_pp0_iter24_reg;
        data_result_addr_reg_445_pp0_iter26_reg <= data_result_addr_reg_445_pp0_iter25_reg;
        data_result_addr_reg_445_pp0_iter27_reg <= data_result_addr_reg_445_pp0_iter26_reg;
        data_result_addr_reg_445_pp0_iter28_reg <= data_result_addr_reg_445_pp0_iter27_reg;
        data_result_addr_reg_445_pp0_iter29_reg <= data_result_addr_reg_445_pp0_iter28_reg;
        data_result_addr_reg_445_pp0_iter2_reg <= data_result_addr_reg_445;
        data_result_addr_reg_445_pp0_iter30_reg <= data_result_addr_reg_445_pp0_iter29_reg;
        data_result_addr_reg_445_pp0_iter31_reg <= data_result_addr_reg_445_pp0_iter30_reg;
        data_result_addr_reg_445_pp0_iter32_reg <= data_result_addr_reg_445_pp0_iter31_reg;
        data_result_addr_reg_445_pp0_iter33_reg <= data_result_addr_reg_445_pp0_iter32_reg;
        data_result_addr_reg_445_pp0_iter34_reg <= data_result_addr_reg_445_pp0_iter33_reg;
        data_result_addr_reg_445_pp0_iter35_reg <= data_result_addr_reg_445_pp0_iter34_reg;
        data_result_addr_reg_445_pp0_iter36_reg <= data_result_addr_reg_445_pp0_iter35_reg;
        data_result_addr_reg_445_pp0_iter37_reg <= data_result_addr_reg_445_pp0_iter36_reg;
        data_result_addr_reg_445_pp0_iter38_reg <= data_result_addr_reg_445_pp0_iter37_reg;
        data_result_addr_reg_445_pp0_iter3_reg <= data_result_addr_reg_445_pp0_iter2_reg;
        data_result_addr_reg_445_pp0_iter4_reg <= data_result_addr_reg_445_pp0_iter3_reg;
        data_result_addr_reg_445_pp0_iter5_reg <= data_result_addr_reg_445_pp0_iter4_reg;
        data_result_addr_reg_445_pp0_iter6_reg <= data_result_addr_reg_445_pp0_iter5_reg;
        data_result_addr_reg_445_pp0_iter7_reg <= data_result_addr_reg_445_pp0_iter6_reg;
        data_result_addr_reg_445_pp0_iter8_reg <= data_result_addr_reg_445_pp0_iter7_reg;
        data_result_addr_reg_445_pp0_iter9_reg <= data_result_addr_reg_445_pp0_iter8_reg;
        lshr_ln72_1_reg_550 <= {{sub_ln72_fu_308_p2[31:1]}};
        lshr_ln72_2_reg_555 <= {{data_a_q0[31:1]}};
        lshr_ln76_1_reg_535 <= {{sub_ln76_fu_274_p2[31:1]}};
        lshr_ln76_2_reg_540 <= {{data_b_q0[31:1]}};
        mul_ln88_reg_570 <= grp_fu_210_p2;
        mul_ln88_reg_570_pp0_iter10_reg <= mul_ln88_reg_570_pp0_iter9_reg;
        mul_ln88_reg_570_pp0_iter11_reg <= mul_ln88_reg_570_pp0_iter10_reg;
        mul_ln88_reg_570_pp0_iter12_reg <= mul_ln88_reg_570_pp0_iter11_reg;
        mul_ln88_reg_570_pp0_iter13_reg <= mul_ln88_reg_570_pp0_iter12_reg;
        mul_ln88_reg_570_pp0_iter14_reg <= mul_ln88_reg_570_pp0_iter13_reg;
        mul_ln88_reg_570_pp0_iter15_reg <= mul_ln88_reg_570_pp0_iter14_reg;
        mul_ln88_reg_570_pp0_iter16_reg <= mul_ln88_reg_570_pp0_iter15_reg;
        mul_ln88_reg_570_pp0_iter17_reg <= mul_ln88_reg_570_pp0_iter16_reg;
        mul_ln88_reg_570_pp0_iter18_reg <= mul_ln88_reg_570_pp0_iter17_reg;
        mul_ln88_reg_570_pp0_iter19_reg <= mul_ln88_reg_570_pp0_iter18_reg;
        mul_ln88_reg_570_pp0_iter20_reg <= mul_ln88_reg_570_pp0_iter19_reg;
        mul_ln88_reg_570_pp0_iter21_reg <= mul_ln88_reg_570_pp0_iter20_reg;
        mul_ln88_reg_570_pp0_iter22_reg <= mul_ln88_reg_570_pp0_iter21_reg;
        mul_ln88_reg_570_pp0_iter23_reg <= mul_ln88_reg_570_pp0_iter22_reg;
        mul_ln88_reg_570_pp0_iter24_reg <= mul_ln88_reg_570_pp0_iter23_reg;
        mul_ln88_reg_570_pp0_iter25_reg <= mul_ln88_reg_570_pp0_iter24_reg;
        mul_ln88_reg_570_pp0_iter26_reg <= mul_ln88_reg_570_pp0_iter25_reg;
        mul_ln88_reg_570_pp0_iter27_reg <= mul_ln88_reg_570_pp0_iter26_reg;
        mul_ln88_reg_570_pp0_iter28_reg <= mul_ln88_reg_570_pp0_iter27_reg;
        mul_ln88_reg_570_pp0_iter29_reg <= mul_ln88_reg_570_pp0_iter28_reg;
        mul_ln88_reg_570_pp0_iter30_reg <= mul_ln88_reg_570_pp0_iter29_reg;
        mul_ln88_reg_570_pp0_iter31_reg <= mul_ln88_reg_570_pp0_iter30_reg;
        mul_ln88_reg_570_pp0_iter32_reg <= mul_ln88_reg_570_pp0_iter31_reg;
        mul_ln88_reg_570_pp0_iter33_reg <= mul_ln88_reg_570_pp0_iter32_reg;
        mul_ln88_reg_570_pp0_iter34_reg <= mul_ln88_reg_570_pp0_iter33_reg;
        mul_ln88_reg_570_pp0_iter35_reg <= mul_ln88_reg_570_pp0_iter34_reg;
        mul_ln88_reg_570_pp0_iter36_reg <= mul_ln88_reg_570_pp0_iter35_reg;
        mul_ln88_reg_570_pp0_iter37_reg <= mul_ln88_reg_570_pp0_iter36_reg;
        mul_ln88_reg_570_pp0_iter38_reg <= mul_ln88_reg_570_pp0_iter37_reg;
        mul_ln88_reg_570_pp0_iter5_reg <= mul_ln88_reg_570;
        mul_ln88_reg_570_pp0_iter6_reg <= mul_ln88_reg_570_pp0_iter5_reg;
        mul_ln88_reg_570_pp0_iter7_reg <= mul_ln88_reg_570_pp0_iter6_reg;
        mul_ln88_reg_570_pp0_iter8_reg <= mul_ln88_reg_570_pp0_iter7_reg;
        mul_ln88_reg_570_pp0_iter9_reg <= mul_ln88_reg_570_pp0_iter8_reg;
        reg_214_pp0_iter10_reg <= reg_214_pp0_iter9_reg;
        reg_214_pp0_iter11_reg <= reg_214_pp0_iter10_reg;
        reg_214_pp0_iter12_reg <= reg_214_pp0_iter11_reg;
        reg_214_pp0_iter13_reg <= reg_214_pp0_iter12_reg;
        reg_214_pp0_iter14_reg <= reg_214_pp0_iter13_reg;
        reg_214_pp0_iter15_reg <= reg_214_pp0_iter14_reg;
        reg_214_pp0_iter16_reg <= reg_214_pp0_iter15_reg;
        reg_214_pp0_iter17_reg <= reg_214_pp0_iter16_reg;
        reg_214_pp0_iter18_reg <= reg_214_pp0_iter17_reg;
        reg_214_pp0_iter19_reg <= reg_214_pp0_iter18_reg;
        reg_214_pp0_iter20_reg <= reg_214_pp0_iter19_reg;
        reg_214_pp0_iter21_reg <= reg_214_pp0_iter20_reg;
        reg_214_pp0_iter22_reg <= reg_214_pp0_iter21_reg;
        reg_214_pp0_iter23_reg <= reg_214_pp0_iter22_reg;
        reg_214_pp0_iter24_reg <= reg_214_pp0_iter23_reg;
        reg_214_pp0_iter25_reg <= reg_214_pp0_iter24_reg;
        reg_214_pp0_iter26_reg <= reg_214_pp0_iter25_reg;
        reg_214_pp0_iter27_reg <= reg_214_pp0_iter26_reg;
        reg_214_pp0_iter28_reg <= reg_214_pp0_iter27_reg;
        reg_214_pp0_iter29_reg <= reg_214_pp0_iter28_reg;
        reg_214_pp0_iter30_reg <= reg_214_pp0_iter29_reg;
        reg_214_pp0_iter31_reg <= reg_214_pp0_iter30_reg;
        reg_214_pp0_iter32_reg <= reg_214_pp0_iter31_reg;
        reg_214_pp0_iter33_reg <= reg_214_pp0_iter32_reg;
        reg_214_pp0_iter34_reg <= reg_214_pp0_iter33_reg;
        reg_214_pp0_iter35_reg <= reg_214_pp0_iter34_reg;
        reg_214_pp0_iter36_reg <= reg_214_pp0_iter35_reg;
        reg_214_pp0_iter37_reg <= reg_214_pp0_iter36_reg;
        reg_214_pp0_iter38_reg <= reg_214_pp0_iter37_reg;
        reg_214_pp0_iter3_reg <= reg_214;
        reg_214_pp0_iter4_reg <= reg_214_pp0_iter3_reg;
        reg_214_pp0_iter5_reg <= reg_214_pp0_iter4_reg;
        reg_214_pp0_iter6_reg <= reg_214_pp0_iter5_reg;
        reg_214_pp0_iter7_reg <= reg_214_pp0_iter6_reg;
        reg_214_pp0_iter8_reg <= reg_214_pp0_iter7_reg;
        reg_214_pp0_iter9_reg <= reg_214_pp0_iter8_reg;
        reg_219_pp0_iter10_reg <= reg_219_pp0_iter9_reg;
        reg_219_pp0_iter11_reg <= reg_219_pp0_iter10_reg;
        reg_219_pp0_iter12_reg <= reg_219_pp0_iter11_reg;
        reg_219_pp0_iter13_reg <= reg_219_pp0_iter12_reg;
        reg_219_pp0_iter14_reg <= reg_219_pp0_iter13_reg;
        reg_219_pp0_iter15_reg <= reg_219_pp0_iter14_reg;
        reg_219_pp0_iter16_reg <= reg_219_pp0_iter15_reg;
        reg_219_pp0_iter17_reg <= reg_219_pp0_iter16_reg;
        reg_219_pp0_iter18_reg <= reg_219_pp0_iter17_reg;
        reg_219_pp0_iter19_reg <= reg_219_pp0_iter18_reg;
        reg_219_pp0_iter20_reg <= reg_219_pp0_iter19_reg;
        reg_219_pp0_iter21_reg <= reg_219_pp0_iter20_reg;
        reg_219_pp0_iter22_reg <= reg_219_pp0_iter21_reg;
        reg_219_pp0_iter23_reg <= reg_219_pp0_iter22_reg;
        reg_219_pp0_iter24_reg <= reg_219_pp0_iter23_reg;
        reg_219_pp0_iter25_reg <= reg_219_pp0_iter24_reg;
        reg_219_pp0_iter26_reg <= reg_219_pp0_iter25_reg;
        reg_219_pp0_iter27_reg <= reg_219_pp0_iter26_reg;
        reg_219_pp0_iter28_reg <= reg_219_pp0_iter27_reg;
        reg_219_pp0_iter29_reg <= reg_219_pp0_iter28_reg;
        reg_219_pp0_iter30_reg <= reg_219_pp0_iter29_reg;
        reg_219_pp0_iter31_reg <= reg_219_pp0_iter30_reg;
        reg_219_pp0_iter32_reg <= reg_219_pp0_iter31_reg;
        reg_219_pp0_iter33_reg <= reg_219_pp0_iter32_reg;
        reg_219_pp0_iter34_reg <= reg_219_pp0_iter33_reg;
        reg_219_pp0_iter35_reg <= reg_219_pp0_iter34_reg;
        reg_219_pp0_iter36_reg <= reg_219_pp0_iter35_reg;
        reg_219_pp0_iter37_reg <= reg_219_pp0_iter36_reg;
        reg_219_pp0_iter38_reg <= reg_219_pp0_iter37_reg;
        reg_219_pp0_iter3_reg <= reg_219;
        reg_219_pp0_iter4_reg <= reg_219_pp0_iter3_reg;
        reg_219_pp0_iter5_reg <= reg_219_pp0_iter4_reg;
        reg_219_pp0_iter6_reg <= reg_219_pp0_iter5_reg;
        reg_219_pp0_iter7_reg <= reg_219_pp0_iter6_reg;
        reg_219_pp0_iter8_reg <= reg_219_pp0_iter7_reg;
        reg_219_pp0_iter9_reg <= reg_219_pp0_iter8_reg;
        sdiv_ln92_reg_575 <= grp_fu_334_p2;
        select_ln72_reg_565 <= select_ln72_fu_371_p3;
        select_ln72_reg_565_pp0_iter10_reg <= select_ln72_reg_565_pp0_iter9_reg;
        select_ln72_reg_565_pp0_iter11_reg <= select_ln72_reg_565_pp0_iter10_reg;
        select_ln72_reg_565_pp0_iter12_reg <= select_ln72_reg_565_pp0_iter11_reg;
        select_ln72_reg_565_pp0_iter13_reg <= select_ln72_reg_565_pp0_iter12_reg;
        select_ln72_reg_565_pp0_iter14_reg <= select_ln72_reg_565_pp0_iter13_reg;
        select_ln72_reg_565_pp0_iter15_reg <= select_ln72_reg_565_pp0_iter14_reg;
        select_ln72_reg_565_pp0_iter16_reg <= select_ln72_reg_565_pp0_iter15_reg;
        select_ln72_reg_565_pp0_iter17_reg <= select_ln72_reg_565_pp0_iter16_reg;
        select_ln72_reg_565_pp0_iter18_reg <= select_ln72_reg_565_pp0_iter17_reg;
        select_ln72_reg_565_pp0_iter19_reg <= select_ln72_reg_565_pp0_iter18_reg;
        select_ln72_reg_565_pp0_iter20_reg <= select_ln72_reg_565_pp0_iter19_reg;
        select_ln72_reg_565_pp0_iter21_reg <= select_ln72_reg_565_pp0_iter20_reg;
        select_ln72_reg_565_pp0_iter22_reg <= select_ln72_reg_565_pp0_iter21_reg;
        select_ln72_reg_565_pp0_iter23_reg <= select_ln72_reg_565_pp0_iter22_reg;
        select_ln72_reg_565_pp0_iter24_reg <= select_ln72_reg_565_pp0_iter23_reg;
        select_ln72_reg_565_pp0_iter25_reg <= select_ln72_reg_565_pp0_iter24_reg;
        select_ln72_reg_565_pp0_iter26_reg <= select_ln72_reg_565_pp0_iter25_reg;
        select_ln72_reg_565_pp0_iter27_reg <= select_ln72_reg_565_pp0_iter26_reg;
        select_ln72_reg_565_pp0_iter28_reg <= select_ln72_reg_565_pp0_iter27_reg;
        select_ln72_reg_565_pp0_iter29_reg <= select_ln72_reg_565_pp0_iter28_reg;
        select_ln72_reg_565_pp0_iter30_reg <= select_ln72_reg_565_pp0_iter29_reg;
        select_ln72_reg_565_pp0_iter31_reg <= select_ln72_reg_565_pp0_iter30_reg;
        select_ln72_reg_565_pp0_iter32_reg <= select_ln72_reg_565_pp0_iter31_reg;
        select_ln72_reg_565_pp0_iter33_reg <= select_ln72_reg_565_pp0_iter32_reg;
        select_ln72_reg_565_pp0_iter34_reg <= select_ln72_reg_565_pp0_iter33_reg;
        select_ln72_reg_565_pp0_iter35_reg <= select_ln72_reg_565_pp0_iter34_reg;
        select_ln72_reg_565_pp0_iter36_reg <= select_ln72_reg_565_pp0_iter35_reg;
        select_ln72_reg_565_pp0_iter37_reg <= select_ln72_reg_565_pp0_iter36_reg;
        select_ln72_reg_565_pp0_iter38_reg <= select_ln72_reg_565_pp0_iter37_reg;
        select_ln72_reg_565_pp0_iter4_reg <= select_ln72_reg_565;
        select_ln72_reg_565_pp0_iter5_reg <= select_ln72_reg_565_pp0_iter4_reg;
        select_ln72_reg_565_pp0_iter6_reg <= select_ln72_reg_565_pp0_iter5_reg;
        select_ln72_reg_565_pp0_iter7_reg <= select_ln72_reg_565_pp0_iter6_reg;
        select_ln72_reg_565_pp0_iter8_reg <= select_ln72_reg_565_pp0_iter7_reg;
        select_ln72_reg_565_pp0_iter9_reg <= select_ln72_reg_565_pp0_iter8_reg;
        select_ln76_reg_560 <= select_ln76_fu_352_p3;
        select_ln76_reg_560_pp0_iter10_reg <= select_ln76_reg_560_pp0_iter9_reg;
        select_ln76_reg_560_pp0_iter11_reg <= select_ln76_reg_560_pp0_iter10_reg;
        select_ln76_reg_560_pp0_iter12_reg <= select_ln76_reg_560_pp0_iter11_reg;
        select_ln76_reg_560_pp0_iter13_reg <= select_ln76_reg_560_pp0_iter12_reg;
        select_ln76_reg_560_pp0_iter14_reg <= select_ln76_reg_560_pp0_iter13_reg;
        select_ln76_reg_560_pp0_iter15_reg <= select_ln76_reg_560_pp0_iter14_reg;
        select_ln76_reg_560_pp0_iter16_reg <= select_ln76_reg_560_pp0_iter15_reg;
        select_ln76_reg_560_pp0_iter17_reg <= select_ln76_reg_560_pp0_iter16_reg;
        select_ln76_reg_560_pp0_iter18_reg <= select_ln76_reg_560_pp0_iter17_reg;
        select_ln76_reg_560_pp0_iter19_reg <= select_ln76_reg_560_pp0_iter18_reg;
        select_ln76_reg_560_pp0_iter20_reg <= select_ln76_reg_560_pp0_iter19_reg;
        select_ln76_reg_560_pp0_iter21_reg <= select_ln76_reg_560_pp0_iter20_reg;
        select_ln76_reg_560_pp0_iter22_reg <= select_ln76_reg_560_pp0_iter21_reg;
        select_ln76_reg_560_pp0_iter23_reg <= select_ln76_reg_560_pp0_iter22_reg;
        select_ln76_reg_560_pp0_iter24_reg <= select_ln76_reg_560_pp0_iter23_reg;
        select_ln76_reg_560_pp0_iter25_reg <= select_ln76_reg_560_pp0_iter24_reg;
        select_ln76_reg_560_pp0_iter26_reg <= select_ln76_reg_560_pp0_iter25_reg;
        select_ln76_reg_560_pp0_iter27_reg <= select_ln76_reg_560_pp0_iter26_reg;
        select_ln76_reg_560_pp0_iter28_reg <= select_ln76_reg_560_pp0_iter27_reg;
        select_ln76_reg_560_pp0_iter29_reg <= select_ln76_reg_560_pp0_iter28_reg;
        select_ln76_reg_560_pp0_iter30_reg <= select_ln76_reg_560_pp0_iter29_reg;
        select_ln76_reg_560_pp0_iter31_reg <= select_ln76_reg_560_pp0_iter30_reg;
        select_ln76_reg_560_pp0_iter32_reg <= select_ln76_reg_560_pp0_iter31_reg;
        select_ln76_reg_560_pp0_iter33_reg <= select_ln76_reg_560_pp0_iter32_reg;
        select_ln76_reg_560_pp0_iter34_reg <= select_ln76_reg_560_pp0_iter33_reg;
        select_ln76_reg_560_pp0_iter35_reg <= select_ln76_reg_560_pp0_iter34_reg;
        select_ln76_reg_560_pp0_iter36_reg <= select_ln76_reg_560_pp0_iter35_reg;
        select_ln76_reg_560_pp0_iter37_reg <= select_ln76_reg_560_pp0_iter36_reg;
        select_ln76_reg_560_pp0_iter38_reg <= select_ln76_reg_560_pp0_iter37_reg;
        select_ln76_reg_560_pp0_iter4_reg <= select_ln76_reg_560;
        select_ln76_reg_560_pp0_iter5_reg <= select_ln76_reg_560_pp0_iter4_reg;
        select_ln76_reg_560_pp0_iter6_reg <= select_ln76_reg_560_pp0_iter5_reg;
        select_ln76_reg_560_pp0_iter7_reg <= select_ln76_reg_560_pp0_iter6_reg;
        select_ln76_reg_560_pp0_iter8_reg <= select_ln76_reg_560_pp0_iter7_reg;
        select_ln76_reg_560_pp0_iter9_reg <= select_ln76_reg_560_pp0_iter8_reg;
        sub_ln84_reg_520 <= sub_ln84_fu_254_p2;
        sub_ln84_reg_520_pp0_iter10_reg <= sub_ln84_reg_520_pp0_iter9_reg;
        sub_ln84_reg_520_pp0_iter11_reg <= sub_ln84_reg_520_pp0_iter10_reg;
        sub_ln84_reg_520_pp0_iter12_reg <= sub_ln84_reg_520_pp0_iter11_reg;
        sub_ln84_reg_520_pp0_iter13_reg <= sub_ln84_reg_520_pp0_iter12_reg;
        sub_ln84_reg_520_pp0_iter14_reg <= sub_ln84_reg_520_pp0_iter13_reg;
        sub_ln84_reg_520_pp0_iter15_reg <= sub_ln84_reg_520_pp0_iter14_reg;
        sub_ln84_reg_520_pp0_iter16_reg <= sub_ln84_reg_520_pp0_iter15_reg;
        sub_ln84_reg_520_pp0_iter17_reg <= sub_ln84_reg_520_pp0_iter16_reg;
        sub_ln84_reg_520_pp0_iter18_reg <= sub_ln84_reg_520_pp0_iter17_reg;
        sub_ln84_reg_520_pp0_iter19_reg <= sub_ln84_reg_520_pp0_iter18_reg;
        sub_ln84_reg_520_pp0_iter20_reg <= sub_ln84_reg_520_pp0_iter19_reg;
        sub_ln84_reg_520_pp0_iter21_reg <= sub_ln84_reg_520_pp0_iter20_reg;
        sub_ln84_reg_520_pp0_iter22_reg <= sub_ln84_reg_520_pp0_iter21_reg;
        sub_ln84_reg_520_pp0_iter23_reg <= sub_ln84_reg_520_pp0_iter22_reg;
        sub_ln84_reg_520_pp0_iter24_reg <= sub_ln84_reg_520_pp0_iter23_reg;
        sub_ln84_reg_520_pp0_iter25_reg <= sub_ln84_reg_520_pp0_iter24_reg;
        sub_ln84_reg_520_pp0_iter26_reg <= sub_ln84_reg_520_pp0_iter25_reg;
        sub_ln84_reg_520_pp0_iter27_reg <= sub_ln84_reg_520_pp0_iter26_reg;
        sub_ln84_reg_520_pp0_iter28_reg <= sub_ln84_reg_520_pp0_iter27_reg;
        sub_ln84_reg_520_pp0_iter29_reg <= sub_ln84_reg_520_pp0_iter28_reg;
        sub_ln84_reg_520_pp0_iter30_reg <= sub_ln84_reg_520_pp0_iter29_reg;
        sub_ln84_reg_520_pp0_iter31_reg <= sub_ln84_reg_520_pp0_iter30_reg;
        sub_ln84_reg_520_pp0_iter32_reg <= sub_ln84_reg_520_pp0_iter31_reg;
        sub_ln84_reg_520_pp0_iter33_reg <= sub_ln84_reg_520_pp0_iter32_reg;
        sub_ln84_reg_520_pp0_iter34_reg <= sub_ln84_reg_520_pp0_iter33_reg;
        sub_ln84_reg_520_pp0_iter35_reg <= sub_ln84_reg_520_pp0_iter34_reg;
        sub_ln84_reg_520_pp0_iter36_reg <= sub_ln84_reg_520_pp0_iter35_reg;
        sub_ln84_reg_520_pp0_iter37_reg <= sub_ln84_reg_520_pp0_iter36_reg;
        sub_ln84_reg_520_pp0_iter38_reg <= sub_ln84_reg_520_pp0_iter37_reg;
        sub_ln84_reg_520_pp0_iter3_reg <= sub_ln84_reg_520;
        sub_ln84_reg_520_pp0_iter4_reg <= sub_ln84_reg_520_pp0_iter3_reg;
        sub_ln84_reg_520_pp0_iter5_reg <= sub_ln84_reg_520_pp0_iter4_reg;
        sub_ln84_reg_520_pp0_iter6_reg <= sub_ln84_reg_520_pp0_iter5_reg;
        sub_ln84_reg_520_pp0_iter7_reg <= sub_ln84_reg_520_pp0_iter6_reg;
        sub_ln84_reg_520_pp0_iter8_reg <= sub_ln84_reg_520_pp0_iter7_reg;
        sub_ln84_reg_520_pp0_iter9_reg <= sub_ln84_reg_520_pp0_iter8_reg;
        tmp_1_reg_530 <= data_b_q0[32'd31];
        tmp_reg_545 <= data_a_q0[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (32'd2 == ALU_operation_load_reg_441) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (32'd8 == ALU_operation_load_reg_441) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (32'd9 == ALU_operation_load_reg_441) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (32'd0 == ALU_operation_load_reg_441)))) begin
        reg_214 <= data_a_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((32'd1 == ALU_operation_load_reg_441) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((32'd3 == ALU_operation_load_reg_441) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (32'd8 == ALU_operation_load_reg_441) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (32'd9 == ALU_operation_load_reg_441) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_219 <= data_b_q0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ALU_operation_ce0 = 1'b1;
    end else begin
        ALU_operation_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_fu_232_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter38_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) 
    & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_58;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_652)) begin
        if ((32'd0 == ALU_operation_q0)) begin
            data_a_address0 = data_a_addr_gep_fu_196_p3;
        end else if ((32'd2 == ALU_operation_q0)) begin
            data_a_address0 = data_a_addr_1_gep_fu_180_p3;
        end else if ((32'd4 == ALU_operation_q0)) begin
            data_a_address0 = data_a_addr_2_gep_fu_164_p3;
        end else if ((32'd6 == ALU_operation_q0)) begin
            data_a_address0 = data_a_addr_3_gep_fu_140_p3;
        end else if ((32'd7 == ALU_operation_q0)) begin
            data_a_address0 = data_a_addr_4_gep_fu_124_p3;
        end else if ((32'd8 == ALU_operation_q0)) begin
            data_a_address0 = data_a_addr_5_gep_fu_108_p3;
        end else if ((32'd9 == ALU_operation_q0)) begin
            data_a_address0 = zext_ln49_reg_417;
        end else begin
            data_a_address0 = 'bx;
        end
    end else begin
        data_a_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((32'd2 == ALU_operation_q0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((32'd4 == ALU_operation_q0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((32'd6 == ALU_operation_q0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((32'd7 == ALU_operation_q0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (32'd8 == ALU_operation_q0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (32'd9 == ALU_operation_q0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (32'd0 == ALU_operation_q0)))) begin
        data_a_ce0 = 1'b1;
    end else begin
        data_a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_652)) begin
        if ((32'd1 == ALU_operation_q0)) begin
            data_b_address0 = data_b_addr_gep_fu_188_p3;
        end else if ((32'd3 == ALU_operation_q0)) begin
            data_b_address0 = data_b_addr_1_gep_fu_172_p3;
        end else if ((32'd5 == ALU_operation_q0)) begin
            data_b_address0 = data_b_addr_2_gep_fu_156_p3;
        end else if ((32'd6 == ALU_operation_q0)) begin
            data_b_address0 = data_b_addr_3_gep_fu_148_p3;
        end else if ((32'd7 == ALU_operation_q0)) begin
            data_b_address0 = data_b_addr_4_gep_fu_132_p3;
        end else if ((32'd8 == ALU_operation_q0)) begin
            data_b_address0 = data_b_addr_5_gep_fu_116_p3;
        end else if ((32'd9 == ALU_operation_q0)) begin
            data_b_address0 = zext_ln49_reg_417;
        end else begin
            data_b_address0 = 'bx;
        end
    end else begin
        data_b_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((32'd1 == ALU_operation_q0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((32'd3 == ALU_operation_q0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((32'd5 == ALU_operation_q0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((32'd6 == ALU_operation_q0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((32'd7 == ALU_operation_q0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (32'd8 == ALU_operation_q0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (32'd9 == ALU_operation_q0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        data_b_ce0 = 1'b1;
    end else begin
        data_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred803_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred777_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred769_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred761_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred753_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred746_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred739_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred732_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred725_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & 
    (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred718_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred712_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)))) begin
        data_result_ce0 = 1'b1;
    end else begin
        data_result_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
        if ((ap_predicate_pred803_state40 == 1'b1)) begin
            data_result_d0 = 32'd0;
        end else if ((ap_predicate_pred777_state40 == 1'b1)) begin
            data_result_d0 = add_ln56_fu_399_p2;
        end else if ((ap_predicate_pred769_state40 == 1'b1)) begin
            data_result_d0 = add_ln60_fu_392_p2;
        end else if ((ap_predicate_pred761_state40 == 1'b1)) begin
            data_result_d0 = shl_ln64_fu_385_p2;
        end else if ((ap_predicate_pred753_state40 == 1'b1)) begin
            data_result_d0 = shl_ln68_fu_378_p2;
        end else if ((ap_predicate_pred746_state40 == 1'b1)) begin
            data_result_d0 = select_ln72_reg_565_pp0_iter38_reg;
        end else if ((ap_predicate_pred739_state40 == 1'b1)) begin
            data_result_d0 = select_ln76_reg_560_pp0_iter38_reg;
        end else if ((ap_predicate_pred732_state40 == 1'b1)) begin
            data_result_d0 = add_ln80_reg_525_pp0_iter38_reg;
        end else if ((ap_predicate_pred725_state40 == 1'b1)) begin
            data_result_d0 = sub_ln84_reg_520_pp0_iter38_reg;
        end else if ((ap_predicate_pred718_state40 == 1'b1)) begin
            data_result_d0 = mul_ln88_reg_570_pp0_iter38_reg;
        end else if ((ap_predicate_pred712_state40 == 1'b1)) begin
            data_result_d0 = sdiv_ln92_reg_575;
        end else begin
            data_result_d0 = 'bx;
        end
    end else begin
        data_result_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred803_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred777_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred769_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred761_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred753_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred746_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred739_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred732_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred725_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & 
    (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred718_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred712_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)))) begin
        data_result_we0 = 1'b1;
    end else begin
        data_result_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ALU_operation_address0 = zext_ln49_fu_244_p1;

assign add_ln49_fu_238_p2 = (ap_sig_allocacmp_i_2 + 6'd1);

assign add_ln56_fu_399_p2 = (reg_214_pp0_iter38_reg + 32'd27);

assign add_ln60_fu_392_p2 = (reg_219_pp0_iter38_reg + 32'd27);

assign add_ln80_fu_260_p2 = (data_b_q0 + data_a_q0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_652 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign data_a_addr_1_gep_fu_180_p3 = zext_ln49_reg_417;

assign data_a_addr_2_gep_fu_164_p3 = zext_ln49_reg_417;

assign data_a_addr_3_gep_fu_140_p3 = zext_ln49_reg_417;

assign data_a_addr_4_gep_fu_124_p3 = zext_ln49_reg_417;

assign data_a_addr_5_gep_fu_108_p3 = zext_ln49_reg_417;

assign data_a_addr_gep_fu_196_p3 = zext_ln49_reg_417;

assign data_b_addr_1_gep_fu_172_p3 = zext_ln49_reg_417;

assign data_b_addr_2_gep_fu_156_p3 = zext_ln49_reg_417;

assign data_b_addr_3_gep_fu_148_p3 = zext_ln49_reg_417;

assign data_b_addr_4_gep_fu_132_p3 = zext_ln49_reg_417;

assign data_b_addr_5_gep_fu_116_p3 = zext_ln49_reg_417;

assign data_b_addr_gep_fu_188_p3 = zext_ln49_reg_417;

assign data_result_address0 = data_result_addr_reg_445_pp0_iter38_reg;

assign icmp_ln49_fu_232_p2 = ((ap_sig_allocacmp_i_2 == 6'd50) ? 1'b1 : 1'b0);

assign select_ln72_fu_371_p3 = ((tmp_reg_545[0:0] == 1'b1) ? sub_ln72_1_fu_362_p2 : zext_ln72_1_fu_368_p1);

assign select_ln76_fu_352_p3 = ((tmp_1_reg_530[0:0] == 1'b1) ? sub_ln76_1_fu_343_p2 : zext_ln76_1_fu_349_p1);

assign shl_ln64_fu_385_p2 = reg_214_pp0_iter38_reg << 32'd1;

assign shl_ln68_fu_378_p2 = reg_219_pp0_iter38_reg << 32'd1;

assign sub_ln72_1_fu_362_p2 = (32'd0 - zext_ln72_fu_359_p1);

assign sub_ln72_fu_308_p2 = (32'd0 - data_a_q0);

assign sub_ln76_1_fu_343_p2 = (32'd0 - zext_ln76_fu_340_p1);

assign sub_ln76_fu_274_p2 = (32'd0 - data_b_q0);

assign sub_ln84_fu_254_p2 = (data_a_q0 - data_b_q0);

assign zext_ln49_fu_244_p1 = ap_sig_allocacmp_i_2;

assign zext_ln72_1_fu_368_p1 = lshr_ln72_2_reg_555;

assign zext_ln72_fu_359_p1 = lshr_ln72_1_reg_550;

assign zext_ln76_1_fu_349_p1 = lshr_ln76_2_reg_540;

assign zext_ln76_fu_340_p1 = lshr_ln76_1_reg_535;

always @ (posedge ap_clk) begin
    zext_ln49_reg_417[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //dec_MIMD_dec_MIMD_Pipeline_VITIS_LOOP_49_1
