// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module alv_MIMD_op_data_exe_wb (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        a,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        b,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RFIFONUM,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        op,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RFIFONUM,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        c,
        ALU_operation_MEM_address0,
        ALU_operation_MEM_ce0,
        ALU_operation_MEM_we0,
        ALU_operation_MEM_d0,
        ALU_operation_MEM_q0,
        ALU_operation_dout,
        ALU_operation_empty_n,
        ALU_operation_read,
        ALU_operation_din,
        ALU_operation_full_n,
        ALU_operation_write,
        data_a_dout,
        data_a_empty_n,
        data_a_read,
        data_a_din,
        data_a_full_n,
        data_a_write,
        data_b_dout,
        data_b_empty_n,
        data_b_read,
        data_b_din,
        data_b_full_n,
        data_b_write,
        data_result_dout,
        data_result_empty_n,
        data_result_read,
        data_result_din,
        data_result_full_n,
        data_result_write
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [31:0] m_axi_gmem0_WDATA;
output  [3:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [31:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] a;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] b;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [63:0] m_axi_gmem3_AWADDR;
output  [0:0] m_axi_gmem3_AWID;
output  [31:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [0:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [31:0] m_axi_gmem3_WDATA;
output  [3:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [0:0] m_axi_gmem3_WID;
output  [0:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [63:0] m_axi_gmem3_ARADDR;
output  [0:0] m_axi_gmem3_ARID;
output  [31:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [0:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [31:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [0:0] m_axi_gmem3_RID;
input  [8:0] m_axi_gmem3_RFIFONUM;
input  [0:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [0:0] m_axi_gmem3_BID;
input  [0:0] m_axi_gmem3_BUSER;
input  [63:0] op;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [63:0] m_axi_gmem2_AWADDR;
output  [0:0] m_axi_gmem2_AWID;
output  [31:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [0:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [31:0] m_axi_gmem2_WDATA;
output  [3:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [0:0] m_axi_gmem2_WID;
output  [0:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [63:0] m_axi_gmem2_ARADDR;
output  [0:0] m_axi_gmem2_ARID;
output  [31:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [0:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [31:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [0:0] m_axi_gmem2_RID;
input  [8:0] m_axi_gmem2_RFIFONUM;
input  [0:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [0:0] m_axi_gmem2_BID;
input  [0:0] m_axi_gmem2_BUSER;
input  [63:0] c;
output  [5:0] ALU_operation_MEM_address0;
output   ALU_operation_MEM_ce0;
output   ALU_operation_MEM_we0;
output  [31:0] ALU_operation_MEM_d0;
input  [31:0] ALU_operation_MEM_q0;
input  [31:0] ALU_operation_dout;
input   ALU_operation_empty_n;
output   ALU_operation_read;
output  [31:0] ALU_operation_din;
input   ALU_operation_full_n;
output   ALU_operation_write;
input  [31:0] data_a_dout;
input   data_a_empty_n;
output   data_a_read;
output  [31:0] data_a_din;
input   data_a_full_n;
output   data_a_write;
input  [31:0] data_b_dout;
input   data_b_empty_n;
output   data_b_read;
output  [31:0] data_b_din;
input   data_b_full_n;
output   data_b_write;
input  [31:0] data_result_dout;
input   data_result_empty_n;
output   data_result_read;
output  [31:0] data_result_din;
input   data_result_full_n;
output   data_result_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem0_ARVALID;
reg m_axi_gmem0_RREADY;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;
reg m_axi_gmem3_ARVALID;
reg m_axi_gmem3_RREADY;
reg m_axi_gmem2_AWVALID;
reg m_axi_gmem2_WVALID;
reg m_axi_gmem2_BREADY;
reg[5:0] ALU_operation_MEM_address0;
reg ALU_operation_MEM_ce0;
reg ALU_operation_MEM_we0;
reg ALU_operation_read;
reg ALU_operation_write;
reg data_a_read;
reg data_a_write;
reg data_b_read;
reg data_b_write;
reg data_result_read;
reg data_result_write;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_start;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_done;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_idle;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_ready;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWVALID;
wire   [63:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWADDR;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWLEN;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWSIZE;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWBURST;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWLOCK;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWCACHE;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWPROT;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWQOS;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWREGION;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWUSER;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WVALID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WDATA;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WSTRB;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WLAST;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WID;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WUSER;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARVALID;
wire   [63:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARADDR;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARLEN;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARSIZE;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARBURST;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARLOCK;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARCACHE;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARPROT;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARQOS;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARREGION;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARUSER;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_RREADY;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_BREADY;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ALU_operation_din;
wire    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ALU_operation_write;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_start;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_done;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_idle;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_ready;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWVALID;
wire   [63:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWADDR;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWLEN;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWBURST;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWPROT;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWQOS;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWREGION;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWUSER;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WVALID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WDATA;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WSTRB;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WLAST;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WID;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WUSER;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARVALID;
wire   [63:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARADDR;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARLEN;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARBURST;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARPROT;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARQOS;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARREGION;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARUSER;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_RREADY;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_BREADY;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_data_a_din;
wire    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_data_a_write;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_start;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_done;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_idle;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_ready;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWVALID;
wire   [63:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWADDR;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWLEN;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWBURST;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWPROT;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWQOS;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWREGION;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWUSER;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WVALID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WDATA;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WSTRB;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WLAST;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WID;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WUSER;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARVALID;
wire   [63:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARADDR;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARLEN;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARBURST;
wire   [1:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARPROT;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARQOS;
wire   [3:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARREGION;
wire   [0:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARUSER;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_RREADY;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_BREADY;
wire   [31:0] grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_data_b_din;
wire    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_data_b_write;
wire    grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_start;
wire    grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_done;
wire    grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_idle;
wire    grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_ready;
wire    grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_read;
wire   [5:0] grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_address0;
wire    grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_ce0;
wire    grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_we0;
wire   [31:0] grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_d0;
wire    grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_start;
wire    grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_done;
wire    grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_idle;
wire    grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_ready;
wire    grp_op_data_exe_wb_Pipeline_exe_fu_127_data_a_read;
wire    grp_op_data_exe_wb_Pipeline_exe_fu_127_data_b_read;
wire   [31:0] grp_op_data_exe_wb_Pipeline_exe_fu_127_data_result_din;
wire    grp_op_data_exe_wb_Pipeline_exe_fu_127_data_result_write;
wire   [5:0] grp_op_data_exe_wb_Pipeline_exe_fu_127_ALU_operation_MEM_address0;
wire    grp_op_data_exe_wb_Pipeline_exe_fu_127_ALU_operation_MEM_ce0;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_start;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_done;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_idle;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_ready;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_data_result_read;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWVALID;
wire   [63:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWADDR;
wire   [0:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWLEN;
wire   [2:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWSIZE;
wire   [1:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWBURST;
wire   [1:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWLOCK;
wire   [3:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWCACHE;
wire   [2:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWPROT;
wire   [3:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWQOS;
wire   [3:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWREGION;
wire   [0:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWUSER;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WVALID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WDATA;
wire   [3:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WSTRB;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WLAST;
wire   [0:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WID;
wire   [0:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WUSER;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARVALID;
wire   [63:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARADDR;
wire   [0:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARID;
wire   [31:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARLEN;
wire   [2:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARSIZE;
wire   [1:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARBURST;
wire   [1:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARLOCK;
wire   [3:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARCACHE;
wire   [2:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARPROT;
wire   [3:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARQOS;
wire   [3:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARREGION;
wire   [0:0] grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARUSER;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_RREADY;
wire    grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_BREADY;
reg    grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg    grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_start_reg;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_start_reg = 1'b0;
#0 grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_start_reg = 1'b0;
#0 grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_start_reg = 1'b0;
#0 grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_start_reg = 1'b0;
#0 grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_start_reg = 1'b0;
#0 grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_start_reg = 1'b0;
end

alv_MIMD_op_data_exe_wb_Pipeline_l_operation grp_op_data_exe_wb_Pipeline_l_operation_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_start),
    .ap_done(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_done),
    .ap_idle(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_idle),
    .ap_ready(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_ready),
    .m_axi_gmem3_AWVALID(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWVALID),
    .m_axi_gmem3_AWREADY(1'b0),
    .m_axi_gmem3_AWADDR(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWADDR),
    .m_axi_gmem3_AWID(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWID),
    .m_axi_gmem3_AWLEN(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWLEN),
    .m_axi_gmem3_AWSIZE(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWSIZE),
    .m_axi_gmem3_AWBURST(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWBURST),
    .m_axi_gmem3_AWLOCK(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWLOCK),
    .m_axi_gmem3_AWCACHE(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWCACHE),
    .m_axi_gmem3_AWPROT(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWPROT),
    .m_axi_gmem3_AWQOS(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWQOS),
    .m_axi_gmem3_AWREGION(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWREGION),
    .m_axi_gmem3_AWUSER(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_AWUSER),
    .m_axi_gmem3_WVALID(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WVALID),
    .m_axi_gmem3_WREADY(1'b0),
    .m_axi_gmem3_WDATA(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WDATA),
    .m_axi_gmem3_WSTRB(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WSTRB),
    .m_axi_gmem3_WLAST(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WLAST),
    .m_axi_gmem3_WID(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WID),
    .m_axi_gmem3_WUSER(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_WUSER),
    .m_axi_gmem3_ARVALID(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARVALID),
    .m_axi_gmem3_ARREADY(m_axi_gmem3_ARREADY),
    .m_axi_gmem3_ARADDR(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARADDR),
    .m_axi_gmem3_ARID(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARID),
    .m_axi_gmem3_ARLEN(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARLEN),
    .m_axi_gmem3_ARSIZE(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARSIZE),
    .m_axi_gmem3_ARBURST(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARBURST),
    .m_axi_gmem3_ARLOCK(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARLOCK),
    .m_axi_gmem3_ARCACHE(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARCACHE),
    .m_axi_gmem3_ARPROT(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARPROT),
    .m_axi_gmem3_ARQOS(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARQOS),
    .m_axi_gmem3_ARREGION(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARREGION),
    .m_axi_gmem3_ARUSER(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARUSER),
    .m_axi_gmem3_RVALID(m_axi_gmem3_RVALID),
    .m_axi_gmem3_RREADY(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_RREADY),
    .m_axi_gmem3_RDATA(m_axi_gmem3_RDATA),
    .m_axi_gmem3_RLAST(m_axi_gmem3_RLAST),
    .m_axi_gmem3_RID(m_axi_gmem3_RID),
    .m_axi_gmem3_RFIFONUM(m_axi_gmem3_RFIFONUM),
    .m_axi_gmem3_RUSER(m_axi_gmem3_RUSER),
    .m_axi_gmem3_RRESP(m_axi_gmem3_RRESP),
    .m_axi_gmem3_BVALID(1'b0),
    .m_axi_gmem3_BREADY(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_BREADY),
    .m_axi_gmem3_BRESP(2'd0),
    .m_axi_gmem3_BID(1'd0),
    .m_axi_gmem3_BUSER(1'd0),
    .ALU_operation_din(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ALU_operation_din),
    .ALU_operation_full_n(ALU_operation_full_n),
    .ALU_operation_write(grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ALU_operation_write),
    .op(op)
);

alv_MIMD_op_data_exe_wb_Pipeline_l_data_a grp_op_data_exe_wb_Pipeline_l_data_a_fu_101(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_start),
    .ap_done(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_done),
    .ap_idle(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_idle),
    .ap_ready(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_ready),
    .m_axi_gmem0_AWVALID(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .data_a_din(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_data_a_din),
    .data_a_full_n(data_a_full_n),
    .data_a_write(grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_data_a_write),
    .a(a)
);

alv_MIMD_op_data_exe_wb_Pipeline_l_data_b grp_op_data_exe_wb_Pipeline_l_data_b_fu_110(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_start),
    .ap_done(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_done),
    .ap_idle(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_idle),
    .ap_ready(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_ready),
    .m_axi_gmem1_AWVALID(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(m_axi_gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(m_axi_gmem1_RVALID),
    .m_axi_gmem1_RREADY(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(m_axi_gmem1_RDATA),
    .m_axi_gmem1_RLAST(m_axi_gmem1_RLAST),
    .m_axi_gmem1_RID(m_axi_gmem1_RID),
    .m_axi_gmem1_RFIFONUM(m_axi_gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(m_axi_gmem1_RUSER),
    .m_axi_gmem1_RRESP(m_axi_gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .data_b_din(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_data_b_din),
    .data_b_full_n(data_b_full_n),
    .data_b_write(grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_data_b_write),
    .b(b)
);

alv_MIMD_op_data_exe_wb_Pipeline_s_operation_data_op grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_start),
    .ap_done(grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_done),
    .ap_idle(grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_idle),
    .ap_ready(grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_ready),
    .ALU_operation_dout(ALU_operation_dout),
    .ALU_operation_empty_n(ALU_operation_empty_n),
    .ALU_operation_read(grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_read),
    .ALU_operation_MEM_address0(grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_address0),
    .ALU_operation_MEM_ce0(grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_ce0),
    .ALU_operation_MEM_we0(grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_we0),
    .ALU_operation_MEM_d0(grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_d0)
);

alv_MIMD_op_data_exe_wb_Pipeline_exe grp_op_data_exe_wb_Pipeline_exe_fu_127(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_start),
    .ap_done(grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_done),
    .ap_idle(grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_idle),
    .ap_ready(grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_ready),
    .data_a_dout(data_a_dout),
    .data_a_empty_n(data_a_empty_n),
    .data_a_read(grp_op_data_exe_wb_Pipeline_exe_fu_127_data_a_read),
    .data_b_dout(data_b_dout),
    .data_b_empty_n(data_b_empty_n),
    .data_b_read(grp_op_data_exe_wb_Pipeline_exe_fu_127_data_b_read),
    .data_result_din(grp_op_data_exe_wb_Pipeline_exe_fu_127_data_result_din),
    .data_result_full_n(data_result_full_n),
    .data_result_write(grp_op_data_exe_wb_Pipeline_exe_fu_127_data_result_write),
    .ALU_operation_MEM_address0(grp_op_data_exe_wb_Pipeline_exe_fu_127_ALU_operation_MEM_address0),
    .ALU_operation_MEM_ce0(grp_op_data_exe_wb_Pipeline_exe_fu_127_ALU_operation_MEM_ce0),
    .ALU_operation_MEM_q0(ALU_operation_MEM_q0)
);

alv_MIMD_op_data_exe_wb_Pipeline_write_back grp_op_data_exe_wb_Pipeline_write_back_fu_139(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_start),
    .ap_done(grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_done),
    .ap_idle(grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_idle),
    .ap_ready(grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_ready),
    .data_result_dout(data_result_dout),
    .data_result_empty_n(data_result_empty_n),
    .data_result_read(grp_op_data_exe_wb_Pipeline_write_back_fu_139_data_result_read),
    .m_axi_gmem2_AWVALID(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(m_axi_gmem2_AWREADY),
    .m_axi_gmem2_AWADDR(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(m_axi_gmem2_WREADY),
    .m_axi_gmem2_WDATA(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(1'b0),
    .m_axi_gmem2_ARADDR(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(1'b0),
    .m_axi_gmem2_RREADY(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(32'd0),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RFIFONUM(9'd0),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(m_axi_gmem2_BVALID),
    .m_axi_gmem2_BREADY(grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(m_axi_gmem2_BRESP),
    .m_axi_gmem2_BID(m_axi_gmem2_BID),
    .m_axi_gmem2_BUSER(m_axi_gmem2_BUSER),
    .c(c)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_start_reg <= 1'b1;
        end else if ((grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_ready == 1'b1)) begin
            grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_start_reg <= 1'b1;
        end else if ((grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_ready == 1'b1)) begin
            grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_start_reg <= 1'b1;
        end else if ((grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_ready == 1'b1)) begin
            grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_ready == 1'b1)) begin
            grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_start_reg <= 1'b1;
        end else if ((grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_ready == 1'b1)) begin
            grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_start_reg <= 1'b1;
        end else if ((grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_ready == 1'b1)) begin
            grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ALU_operation_MEM_address0 = grp_op_data_exe_wb_Pipeline_exe_fu_127_ALU_operation_MEM_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        ALU_operation_MEM_address0 = grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_address0;
    end else begin
        ALU_operation_MEM_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ALU_operation_MEM_ce0 = grp_op_data_exe_wb_Pipeline_exe_fu_127_ALU_operation_MEM_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        ALU_operation_MEM_ce0 = grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_ce0;
    end else begin
        ALU_operation_MEM_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ALU_operation_MEM_we0 = grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_we0;
    end else begin
        ALU_operation_MEM_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ALU_operation_read = grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_read;
    end else begin
        ALU_operation_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ALU_operation_write = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ALU_operation_write;
    end else begin
        ALU_operation_write = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_a_read = grp_op_data_exe_wb_Pipeline_exe_fu_127_data_a_read;
    end else begin
        data_a_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_a_write = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_data_a_write;
    end else begin
        data_a_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_b_read = grp_op_data_exe_wb_Pipeline_exe_fu_127_data_b_read;
    end else begin
        data_b_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        data_b_write = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_data_b_write;
    end else begin
        data_b_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        data_result_read = grp_op_data_exe_wb_Pipeline_write_back_fu_139_data_result_read;
    end else begin
        data_result_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_result_write = grp_op_data_exe_wb_Pipeline_exe_fu_127_data_result_write;
    end else begin
        data_result_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        m_axi_gmem0_ARVALID = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARVALID;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        m_axi_gmem0_RREADY = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_RREADY;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_gmem1_ARVALID = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARVALID;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_gmem1_RREADY = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_RREADY;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        m_axi_gmem2_AWVALID = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWVALID;
    end else begin
        m_axi_gmem2_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        m_axi_gmem2_BREADY = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_BREADY;
    end else begin
        m_axi_gmem2_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        m_axi_gmem2_WVALID = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WVALID;
    end else begin
        m_axi_gmem2_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem3_ARVALID = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARVALID;
    end else begin
        m_axi_gmem3_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem3_RREADY = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_RREADY;
    end else begin
        m_axi_gmem3_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ALU_operation_MEM_d0 = grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ALU_operation_MEM_d0;

assign ALU_operation_din = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ALU_operation_din;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign data_a_din = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_data_a_din;

assign data_b_din = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_data_b_din;

assign data_result_din = grp_op_data_exe_wb_Pipeline_exe_fu_127_data_result_din;

assign grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_start = grp_op_data_exe_wb_Pipeline_exe_fu_127_ap_start_reg;

assign grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_start = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_ap_start_reg;

assign grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_start = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_ap_start_reg;

assign grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_start = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_ap_start_reg;

assign grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_start = grp_op_data_exe_wb_Pipeline_s_operation_data_op_fu_119_ap_start_reg;

assign grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_start = grp_op_data_exe_wb_Pipeline_write_back_fu_139_ap_start_reg;

assign m_axi_gmem0_ARADDR = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARADDR;

assign m_axi_gmem0_ARBURST = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARBURST;

assign m_axi_gmem0_ARCACHE = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARCACHE;

assign m_axi_gmem0_ARID = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARID;

assign m_axi_gmem0_ARLEN = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARLEN;

assign m_axi_gmem0_ARLOCK = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARLOCK;

assign m_axi_gmem0_ARPROT = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARPROT;

assign m_axi_gmem0_ARQOS = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARQOS;

assign m_axi_gmem0_ARREGION = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARREGION;

assign m_axi_gmem0_ARSIZE = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARSIZE;

assign m_axi_gmem0_ARUSER = grp_op_data_exe_wb_Pipeline_l_data_a_fu_101_m_axi_gmem0_ARUSER;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 32'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 4'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign m_axi_gmem1_ARADDR = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARADDR;

assign m_axi_gmem1_ARBURST = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARBURST;

assign m_axi_gmem1_ARCACHE = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARCACHE;

assign m_axi_gmem1_ARID = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARID;

assign m_axi_gmem1_ARLEN = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARLEN;

assign m_axi_gmem1_ARLOCK = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARLOCK;

assign m_axi_gmem1_ARPROT = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARPROT;

assign m_axi_gmem1_ARQOS = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARQOS;

assign m_axi_gmem1_ARREGION = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARREGION;

assign m_axi_gmem1_ARSIZE = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARSIZE;

assign m_axi_gmem1_ARUSER = grp_op_data_exe_wb_Pipeline_l_data_b_fu_110_m_axi_gmem1_ARUSER;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 32'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 4'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign m_axi_gmem2_ARADDR = 64'd0;

assign m_axi_gmem2_ARBURST = 2'd0;

assign m_axi_gmem2_ARCACHE = 4'd0;

assign m_axi_gmem2_ARID = 1'd0;

assign m_axi_gmem2_ARLEN = 32'd0;

assign m_axi_gmem2_ARLOCK = 2'd0;

assign m_axi_gmem2_ARPROT = 3'd0;

assign m_axi_gmem2_ARQOS = 4'd0;

assign m_axi_gmem2_ARREGION = 4'd0;

assign m_axi_gmem2_ARSIZE = 3'd0;

assign m_axi_gmem2_ARUSER = 1'd0;

assign m_axi_gmem2_ARVALID = 1'b0;

assign m_axi_gmem2_AWADDR = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWADDR;

assign m_axi_gmem2_AWBURST = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWBURST;

assign m_axi_gmem2_AWCACHE = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWCACHE;

assign m_axi_gmem2_AWID = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWID;

assign m_axi_gmem2_AWLEN = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWLEN;

assign m_axi_gmem2_AWLOCK = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWLOCK;

assign m_axi_gmem2_AWPROT = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWPROT;

assign m_axi_gmem2_AWQOS = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWQOS;

assign m_axi_gmem2_AWREGION = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWREGION;

assign m_axi_gmem2_AWSIZE = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWSIZE;

assign m_axi_gmem2_AWUSER = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_AWUSER;

assign m_axi_gmem2_RREADY = 1'b0;

assign m_axi_gmem2_WDATA = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WDATA;

assign m_axi_gmem2_WID = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WID;

assign m_axi_gmem2_WLAST = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WLAST;

assign m_axi_gmem2_WSTRB = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WSTRB;

assign m_axi_gmem2_WUSER = grp_op_data_exe_wb_Pipeline_write_back_fu_139_m_axi_gmem2_WUSER;

assign m_axi_gmem3_ARADDR = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARADDR;

assign m_axi_gmem3_ARBURST = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARBURST;

assign m_axi_gmem3_ARCACHE = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARCACHE;

assign m_axi_gmem3_ARID = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARID;

assign m_axi_gmem3_ARLEN = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARLEN;

assign m_axi_gmem3_ARLOCK = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARLOCK;

assign m_axi_gmem3_ARPROT = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARPROT;

assign m_axi_gmem3_ARQOS = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARQOS;

assign m_axi_gmem3_ARREGION = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARREGION;

assign m_axi_gmem3_ARSIZE = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARSIZE;

assign m_axi_gmem3_ARUSER = grp_op_data_exe_wb_Pipeline_l_operation_fu_92_m_axi_gmem3_ARUSER;

assign m_axi_gmem3_AWADDR = 64'd0;

assign m_axi_gmem3_AWBURST = 2'd0;

assign m_axi_gmem3_AWCACHE = 4'd0;

assign m_axi_gmem3_AWID = 1'd0;

assign m_axi_gmem3_AWLEN = 32'd0;

assign m_axi_gmem3_AWLOCK = 2'd0;

assign m_axi_gmem3_AWPROT = 3'd0;

assign m_axi_gmem3_AWQOS = 4'd0;

assign m_axi_gmem3_AWREGION = 4'd0;

assign m_axi_gmem3_AWSIZE = 3'd0;

assign m_axi_gmem3_AWUSER = 1'd0;

assign m_axi_gmem3_AWVALID = 1'b0;

assign m_axi_gmem3_BREADY = 1'b0;

assign m_axi_gmem3_WDATA = 32'd0;

assign m_axi_gmem3_WID = 1'd0;

assign m_axi_gmem3_WLAST = 1'b0;

assign m_axi_gmem3_WSTRB = 4'd0;

assign m_axi_gmem3_WUSER = 1'd0;

assign m_axi_gmem3_WVALID = 1'b0;

endmodule //alv_MIMD_op_data_exe_wb
