# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lotto/Desktop/Alveare/M_AXI_ALU/100/Vivado/ALU_sys_HDL.srcs/sources_1/bd/ALU_sys_HDL_design/ip/ALU_sys_HDL_design_auto_pc_0/ALU_sys_HDL_design_auto_pc_0.xci
# IP: The module: 'ALU_sys_HDL_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lotto/Desktop/Alveare/M_AXI_ALU/100/Vivado/ALU_sys_HDL.gen/sources_1/bd/ALU_sys_HDL_design/ip/ALU_sys_HDL_design_auto_pc_0/ALU_sys_HDL_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ALU_sys_HDL_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/lotto/Desktop/Alveare/M_AXI_ALU/100/Vivado/ALU_sys_HDL.srcs/sources_1/bd/ALU_sys_HDL_design/ip/ALU_sys_HDL_design_auto_pc_0/ALU_sys_HDL_design_auto_pc_0.xci
# IP: The module: 'ALU_sys_HDL_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lotto/Desktop/Alveare/M_AXI_ALU/100/Vivado/ALU_sys_HDL.gen/sources_1/bd/ALU_sys_HDL_design/ip/ALU_sys_HDL_design_auto_pc_0/ALU_sys_HDL_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ALU_sys_HDL_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
