// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module alv_MIMD_execute (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ALU_operation_dout,
        ALU_operation_empty_n,
        ALU_operation_read,
        data_a_dout,
        data_a_empty_n,
        data_a_read,
        data_b_dout,
        data_b_empty_n,
        data_b_read,
        data_result_din,
        data_result_full_n,
        data_result_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] ALU_operation_dout;
input   ALU_operation_empty_n;
output   ALU_operation_read;
input  [31:0] data_a_dout;
input   data_a_empty_n;
output   data_a_read;
input  [31:0] data_b_dout;
input   data_b_empty_n;
output   data_b_read;
output  [31:0] data_result_din;
input   data_result_full_n;
output   data_result_write;

reg ap_idle;
reg ALU_operation_read;
reg data_a_read;
reg data_b_read;
reg[31:0] data_result_din;
reg data_result_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [31:0] ALU_operation_read_reg_296;
reg    ap_block_state3_pp0_stage0_iter2;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter38_reg;
reg    ap_predicate_op155_write_state40;
reg    ap_block_state40_pp0_stage0_iter39;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln82_fu_116_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    data_a_blk_n;
wire    ap_block_pp0_stage0;
reg    data_b_blk_n;
reg    ALU_operation_blk_n;
reg    data_result_blk_n;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter37_reg;
reg    ap_block_pp0_stage0_11001;
reg    ap_predicate_pred325_state40;
reg    ap_predicate_pred332_state40;
reg    ap_predicate_pred337_state40;
reg    ap_predicate_pred342_state40;
reg    ap_predicate_pred347_state40;
reg    ap_predicate_pred352_state40;
reg    ap_predicate_pred357_state40;
reg    ap_predicate_pred362_state40;
reg    ap_predicate_pred367_state40;
reg    ap_predicate_pred372_state40;
reg   [31:0] reg_98;
reg   [31:0] reg_98_pp0_iter3_reg;
reg   [31:0] reg_98_pp0_iter4_reg;
reg   [31:0] reg_98_pp0_iter5_reg;
reg   [31:0] reg_98_pp0_iter6_reg;
reg   [31:0] reg_98_pp0_iter7_reg;
reg   [31:0] reg_98_pp0_iter8_reg;
reg   [31:0] reg_98_pp0_iter9_reg;
reg   [31:0] reg_98_pp0_iter10_reg;
reg   [31:0] reg_98_pp0_iter11_reg;
reg   [31:0] reg_98_pp0_iter12_reg;
reg   [31:0] reg_98_pp0_iter13_reg;
reg   [31:0] reg_98_pp0_iter14_reg;
reg   [31:0] reg_98_pp0_iter15_reg;
reg   [31:0] reg_98_pp0_iter16_reg;
reg   [31:0] reg_98_pp0_iter17_reg;
reg   [31:0] reg_98_pp0_iter18_reg;
reg   [31:0] reg_98_pp0_iter19_reg;
reg   [31:0] reg_98_pp0_iter20_reg;
reg   [31:0] reg_98_pp0_iter21_reg;
reg   [31:0] reg_98_pp0_iter22_reg;
reg   [31:0] reg_98_pp0_iter23_reg;
reg   [31:0] reg_98_pp0_iter24_reg;
reg   [31:0] reg_98_pp0_iter25_reg;
reg   [31:0] reg_98_pp0_iter26_reg;
reg   [31:0] reg_98_pp0_iter27_reg;
reg   [31:0] reg_98_pp0_iter28_reg;
reg   [31:0] reg_98_pp0_iter29_reg;
reg   [31:0] reg_98_pp0_iter30_reg;
reg   [31:0] reg_98_pp0_iter31_reg;
reg   [31:0] reg_98_pp0_iter32_reg;
reg   [31:0] reg_98_pp0_iter33_reg;
reg   [31:0] reg_98_pp0_iter34_reg;
reg   [31:0] reg_98_pp0_iter35_reg;
reg   [31:0] reg_98_pp0_iter36_reg;
reg   [31:0] reg_98_pp0_iter37_reg;
reg   [31:0] reg_98_pp0_iter38_reg;
reg   [31:0] reg_103;
reg   [31:0] reg_103_pp0_iter3_reg;
reg   [31:0] reg_103_pp0_iter4_reg;
reg   [31:0] reg_103_pp0_iter5_reg;
reg   [31:0] reg_103_pp0_iter6_reg;
reg   [31:0] reg_103_pp0_iter7_reg;
reg   [31:0] reg_103_pp0_iter8_reg;
reg   [31:0] reg_103_pp0_iter9_reg;
reg   [31:0] reg_103_pp0_iter10_reg;
reg   [31:0] reg_103_pp0_iter11_reg;
reg   [31:0] reg_103_pp0_iter12_reg;
reg   [31:0] reg_103_pp0_iter13_reg;
reg   [31:0] reg_103_pp0_iter14_reg;
reg   [31:0] reg_103_pp0_iter15_reg;
reg   [31:0] reg_103_pp0_iter16_reg;
reg   [31:0] reg_103_pp0_iter17_reg;
reg   [31:0] reg_103_pp0_iter18_reg;
reg   [31:0] reg_103_pp0_iter19_reg;
reg   [31:0] reg_103_pp0_iter20_reg;
reg   [31:0] reg_103_pp0_iter21_reg;
reg   [31:0] reg_103_pp0_iter22_reg;
reg   [31:0] reg_103_pp0_iter23_reg;
reg   [31:0] reg_103_pp0_iter24_reg;
reg   [31:0] reg_103_pp0_iter25_reg;
reg   [31:0] reg_103_pp0_iter26_reg;
reg   [31:0] reg_103_pp0_iter27_reg;
reg   [31:0] reg_103_pp0_iter28_reg;
reg   [31:0] reg_103_pp0_iter29_reg;
reg   [31:0] reg_103_pp0_iter30_reg;
reg   [31:0] reg_103_pp0_iter31_reg;
reg   [31:0] reg_103_pp0_iter32_reg;
reg   [31:0] reg_103_pp0_iter33_reg;
reg   [31:0] reg_103_pp0_iter34_reg;
reg   [31:0] reg_103_pp0_iter35_reg;
reg   [31:0] reg_103_pp0_iter36_reg;
reg   [31:0] reg_103_pp0_iter37_reg;
reg   [31:0] reg_103_pp0_iter38_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter2_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter3_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter4_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter5_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter6_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter7_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter8_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter9_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter10_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter11_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter12_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter13_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter14_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter15_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter16_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter17_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter18_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter19_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter20_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter21_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter22_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter23_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter24_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter25_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter26_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter27_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter28_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter29_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter30_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter31_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter32_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter33_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter34_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter35_reg;
reg   [31:0] ALU_operation_read_reg_296_pp0_iter36_reg;
wire   [31:0] sub_ln118_fu_133_p2;
reg   [31:0] sub_ln118_reg_300;
reg   [31:0] sub_ln118_reg_300_pp0_iter3_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter4_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter5_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter6_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter7_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter8_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter9_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter10_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter11_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter12_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter13_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter14_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter15_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter16_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter17_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter18_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter19_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter20_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter21_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter22_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter23_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter24_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter25_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter26_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter27_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter28_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter29_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter30_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter31_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter32_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter33_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter34_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter35_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter36_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter37_reg;
reg   [31:0] sub_ln118_reg_300_pp0_iter38_reg;
wire   [31:0] add_ln114_fu_139_p2;
reg   [31:0] add_ln114_reg_305;
reg   [31:0] add_ln114_reg_305_pp0_iter3_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter4_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter5_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter6_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter7_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter8_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter9_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter10_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter11_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter12_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter13_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter14_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter15_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter16_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter17_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter18_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter19_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter20_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter21_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter22_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter23_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter24_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter25_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter26_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter27_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter28_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter29_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter30_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter31_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter32_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter33_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter34_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter35_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter36_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter37_reg;
reg   [31:0] add_ln114_reg_305_pp0_iter38_reg;
reg   [0:0] tmp_1_reg_310;
reg   [30:0] lshr_ln110_1_reg_315;
reg   [30:0] lshr_ln110_2_reg_320;
reg   [0:0] tmp_reg_325;
reg   [30:0] lshr_ln106_1_reg_330;
reg   [30:0] lshr_ln106_2_reg_335;
wire   [31:0] select_ln110_fu_231_p3;
reg   [31:0] select_ln110_reg_340;
reg   [31:0] select_ln110_reg_340_pp0_iter4_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter5_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter6_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter7_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter8_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter9_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter10_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter11_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter12_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter13_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter14_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter15_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter16_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter17_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter18_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter19_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter20_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter21_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter22_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter23_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter24_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter25_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter26_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter27_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter28_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter29_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter30_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter31_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter32_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter33_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter34_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter35_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter36_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter37_reg;
reg   [31:0] select_ln110_reg_340_pp0_iter38_reg;
wire   [31:0] select_ln106_fu_250_p3;
reg   [31:0] select_ln106_reg_345;
reg   [31:0] select_ln106_reg_345_pp0_iter4_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter5_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter6_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter7_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter8_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter9_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter10_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter11_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter12_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter13_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter14_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter15_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter16_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter17_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter18_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter19_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter20_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter21_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter22_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter23_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter24_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter25_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter26_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter27_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter28_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter29_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter30_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter31_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter32_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter33_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter34_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter35_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter36_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter37_reg;
reg   [31:0] select_ln106_reg_345_pp0_iter38_reg;
wire   [31:0] grp_fu_94_p2;
reg   [31:0] mul_ln122_reg_350;
reg   [31:0] mul_ln122_reg_350_pp0_iter5_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter6_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter7_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter8_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter9_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter10_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter11_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter12_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter13_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter14_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter15_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter16_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter17_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter18_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter19_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter20_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter21_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter22_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter23_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter24_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter25_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter26_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter27_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter28_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter29_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter30_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter31_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter32_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter33_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter34_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter35_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter36_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter37_reg;
reg   [31:0] mul_ln122_reg_350_pp0_iter38_reg;
wire   [31:0] grp_fu_213_p2;
reg   [31:0] sdiv_ln126_reg_355;
reg   [5:0] i_fu_64;
wire   [5:0] i_2_fu_122_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] shl_ln102_fu_257_p2;
wire   [31:0] shl_ln98_fu_264_p2;
wire   [31:0] add_ln94_fu_271_p2;
wire   [31:0] add_ln90_fu_278_p2;
wire   [31:0] sub_ln110_fu_153_p2;
wire   [31:0] sub_ln106_fu_187_p2;
wire   [31:0] zext_ln110_fu_219_p1;
wire   [31:0] sub_ln110_1_fu_222_p2;
wire   [31:0] zext_ln110_1_fu_228_p1;
wire   [31:0] zext_ln106_fu_238_p1;
wire   [31:0] sub_ln106_1_fu_241_p2;
wire   [31:0] zext_ln106_1_fu_247_p1;
reg    grp_fu_94_ce;
reg    grp_fu_213_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 i_fu_64 = 6'd0;
#0 ap_done_reg = 1'b0;
end

alv_MIMD_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_103),
    .din1(reg_98),
    .ce(grp_fu_94_ce),
    .dout(grp_fu_94_p2)
);

alv_MIMD_sdiv_32ns_32ns_32_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_98),
    .din1(reg_103),
    .ce(grp_fu_213_ce),
    .dout(grp_fu_213_p2)
);

alv_MIMD_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter38_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln82_fu_116_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_64 <= i_2_fu_122_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_64 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ALU_operation_read_reg_296 <= ALU_operation_dout;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ALU_operation_read_reg_296_pp0_iter10_reg <= ALU_operation_read_reg_296_pp0_iter9_reg;
        ALU_operation_read_reg_296_pp0_iter11_reg <= ALU_operation_read_reg_296_pp0_iter10_reg;
        ALU_operation_read_reg_296_pp0_iter12_reg <= ALU_operation_read_reg_296_pp0_iter11_reg;
        ALU_operation_read_reg_296_pp0_iter13_reg <= ALU_operation_read_reg_296_pp0_iter12_reg;
        ALU_operation_read_reg_296_pp0_iter14_reg <= ALU_operation_read_reg_296_pp0_iter13_reg;
        ALU_operation_read_reg_296_pp0_iter15_reg <= ALU_operation_read_reg_296_pp0_iter14_reg;
        ALU_operation_read_reg_296_pp0_iter16_reg <= ALU_operation_read_reg_296_pp0_iter15_reg;
        ALU_operation_read_reg_296_pp0_iter17_reg <= ALU_operation_read_reg_296_pp0_iter16_reg;
        ALU_operation_read_reg_296_pp0_iter18_reg <= ALU_operation_read_reg_296_pp0_iter17_reg;
        ALU_operation_read_reg_296_pp0_iter19_reg <= ALU_operation_read_reg_296_pp0_iter18_reg;
        ALU_operation_read_reg_296_pp0_iter20_reg <= ALU_operation_read_reg_296_pp0_iter19_reg;
        ALU_operation_read_reg_296_pp0_iter21_reg <= ALU_operation_read_reg_296_pp0_iter20_reg;
        ALU_operation_read_reg_296_pp0_iter22_reg <= ALU_operation_read_reg_296_pp0_iter21_reg;
        ALU_operation_read_reg_296_pp0_iter23_reg <= ALU_operation_read_reg_296_pp0_iter22_reg;
        ALU_operation_read_reg_296_pp0_iter24_reg <= ALU_operation_read_reg_296_pp0_iter23_reg;
        ALU_operation_read_reg_296_pp0_iter25_reg <= ALU_operation_read_reg_296_pp0_iter24_reg;
        ALU_operation_read_reg_296_pp0_iter26_reg <= ALU_operation_read_reg_296_pp0_iter25_reg;
        ALU_operation_read_reg_296_pp0_iter27_reg <= ALU_operation_read_reg_296_pp0_iter26_reg;
        ALU_operation_read_reg_296_pp0_iter28_reg <= ALU_operation_read_reg_296_pp0_iter27_reg;
        ALU_operation_read_reg_296_pp0_iter29_reg <= ALU_operation_read_reg_296_pp0_iter28_reg;
        ALU_operation_read_reg_296_pp0_iter2_reg <= ALU_operation_read_reg_296;
        ALU_operation_read_reg_296_pp0_iter30_reg <= ALU_operation_read_reg_296_pp0_iter29_reg;
        ALU_operation_read_reg_296_pp0_iter31_reg <= ALU_operation_read_reg_296_pp0_iter30_reg;
        ALU_operation_read_reg_296_pp0_iter32_reg <= ALU_operation_read_reg_296_pp0_iter31_reg;
        ALU_operation_read_reg_296_pp0_iter33_reg <= ALU_operation_read_reg_296_pp0_iter32_reg;
        ALU_operation_read_reg_296_pp0_iter34_reg <= ALU_operation_read_reg_296_pp0_iter33_reg;
        ALU_operation_read_reg_296_pp0_iter35_reg <= ALU_operation_read_reg_296_pp0_iter34_reg;
        ALU_operation_read_reg_296_pp0_iter36_reg <= ALU_operation_read_reg_296_pp0_iter35_reg;
        ALU_operation_read_reg_296_pp0_iter37_reg <= ALU_operation_read_reg_296_pp0_iter36_reg;
        ALU_operation_read_reg_296_pp0_iter38_reg <= ALU_operation_read_reg_296_pp0_iter37_reg;
        ALU_operation_read_reg_296_pp0_iter3_reg <= ALU_operation_read_reg_296_pp0_iter2_reg;
        ALU_operation_read_reg_296_pp0_iter4_reg <= ALU_operation_read_reg_296_pp0_iter3_reg;
        ALU_operation_read_reg_296_pp0_iter5_reg <= ALU_operation_read_reg_296_pp0_iter4_reg;
        ALU_operation_read_reg_296_pp0_iter6_reg <= ALU_operation_read_reg_296_pp0_iter5_reg;
        ALU_operation_read_reg_296_pp0_iter7_reg <= ALU_operation_read_reg_296_pp0_iter6_reg;
        ALU_operation_read_reg_296_pp0_iter8_reg <= ALU_operation_read_reg_296_pp0_iter7_reg;
        ALU_operation_read_reg_296_pp0_iter9_reg <= ALU_operation_read_reg_296_pp0_iter8_reg;
        add_ln114_reg_305 <= add_ln114_fu_139_p2;
        add_ln114_reg_305_pp0_iter10_reg <= add_ln114_reg_305_pp0_iter9_reg;
        add_ln114_reg_305_pp0_iter11_reg <= add_ln114_reg_305_pp0_iter10_reg;
        add_ln114_reg_305_pp0_iter12_reg <= add_ln114_reg_305_pp0_iter11_reg;
        add_ln114_reg_305_pp0_iter13_reg <= add_ln114_reg_305_pp0_iter12_reg;
        add_ln114_reg_305_pp0_iter14_reg <= add_ln114_reg_305_pp0_iter13_reg;
        add_ln114_reg_305_pp0_iter15_reg <= add_ln114_reg_305_pp0_iter14_reg;
        add_ln114_reg_305_pp0_iter16_reg <= add_ln114_reg_305_pp0_iter15_reg;
        add_ln114_reg_305_pp0_iter17_reg <= add_ln114_reg_305_pp0_iter16_reg;
        add_ln114_reg_305_pp0_iter18_reg <= add_ln114_reg_305_pp0_iter17_reg;
        add_ln114_reg_305_pp0_iter19_reg <= add_ln114_reg_305_pp0_iter18_reg;
        add_ln114_reg_305_pp0_iter20_reg <= add_ln114_reg_305_pp0_iter19_reg;
        add_ln114_reg_305_pp0_iter21_reg <= add_ln114_reg_305_pp0_iter20_reg;
        add_ln114_reg_305_pp0_iter22_reg <= add_ln114_reg_305_pp0_iter21_reg;
        add_ln114_reg_305_pp0_iter23_reg <= add_ln114_reg_305_pp0_iter22_reg;
        add_ln114_reg_305_pp0_iter24_reg <= add_ln114_reg_305_pp0_iter23_reg;
        add_ln114_reg_305_pp0_iter25_reg <= add_ln114_reg_305_pp0_iter24_reg;
        add_ln114_reg_305_pp0_iter26_reg <= add_ln114_reg_305_pp0_iter25_reg;
        add_ln114_reg_305_pp0_iter27_reg <= add_ln114_reg_305_pp0_iter26_reg;
        add_ln114_reg_305_pp0_iter28_reg <= add_ln114_reg_305_pp0_iter27_reg;
        add_ln114_reg_305_pp0_iter29_reg <= add_ln114_reg_305_pp0_iter28_reg;
        add_ln114_reg_305_pp0_iter30_reg <= add_ln114_reg_305_pp0_iter29_reg;
        add_ln114_reg_305_pp0_iter31_reg <= add_ln114_reg_305_pp0_iter30_reg;
        add_ln114_reg_305_pp0_iter32_reg <= add_ln114_reg_305_pp0_iter31_reg;
        add_ln114_reg_305_pp0_iter33_reg <= add_ln114_reg_305_pp0_iter32_reg;
        add_ln114_reg_305_pp0_iter34_reg <= add_ln114_reg_305_pp0_iter33_reg;
        add_ln114_reg_305_pp0_iter35_reg <= add_ln114_reg_305_pp0_iter34_reg;
        add_ln114_reg_305_pp0_iter36_reg <= add_ln114_reg_305_pp0_iter35_reg;
        add_ln114_reg_305_pp0_iter37_reg <= add_ln114_reg_305_pp0_iter36_reg;
        add_ln114_reg_305_pp0_iter38_reg <= add_ln114_reg_305_pp0_iter37_reg;
        add_ln114_reg_305_pp0_iter3_reg <= add_ln114_reg_305;
        add_ln114_reg_305_pp0_iter4_reg <= add_ln114_reg_305_pp0_iter3_reg;
        add_ln114_reg_305_pp0_iter5_reg <= add_ln114_reg_305_pp0_iter4_reg;
        add_ln114_reg_305_pp0_iter6_reg <= add_ln114_reg_305_pp0_iter5_reg;
        add_ln114_reg_305_pp0_iter7_reg <= add_ln114_reg_305_pp0_iter6_reg;
        add_ln114_reg_305_pp0_iter8_reg <= add_ln114_reg_305_pp0_iter7_reg;
        add_ln114_reg_305_pp0_iter9_reg <= add_ln114_reg_305_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        ap_predicate_pred325_state40 <= (32'd0 == ALU_operation_read_reg_296_pp0_iter37_reg);
        ap_predicate_pred332_state40 <= (32'd1 == ALU_operation_read_reg_296_pp0_iter37_reg);
        ap_predicate_pred337_state40 <= (32'd2 == ALU_operation_read_reg_296_pp0_iter37_reg);
        ap_predicate_pred342_state40 <= (32'd3 == ALU_operation_read_reg_296_pp0_iter37_reg);
        ap_predicate_pred347_state40 <= (32'd4 == ALU_operation_read_reg_296_pp0_iter37_reg);
        ap_predicate_pred352_state40 <= (32'd5 == ALU_operation_read_reg_296_pp0_iter37_reg);
        ap_predicate_pred357_state40 <= (32'd6 == ALU_operation_read_reg_296_pp0_iter37_reg);
        ap_predicate_pred362_state40 <= (32'd7 == ALU_operation_read_reg_296_pp0_iter37_reg);
        ap_predicate_pred367_state40 <= (32'd8 == ALU_operation_read_reg_296_pp0_iter37_reg);
        ap_predicate_pred372_state40 <= (32'd9 == ALU_operation_read_reg_296_pp0_iter37_reg);
        lshr_ln106_1_reg_330 <= {{sub_ln106_fu_187_p2[31:1]}};
        lshr_ln106_2_reg_335 <= {{data_a_dout[31:1]}};
        lshr_ln110_1_reg_315 <= {{sub_ln110_fu_153_p2[31:1]}};
        lshr_ln110_2_reg_320 <= {{data_b_dout[31:1]}};
        mul_ln122_reg_350 <= grp_fu_94_p2;
        mul_ln122_reg_350_pp0_iter10_reg <= mul_ln122_reg_350_pp0_iter9_reg;
        mul_ln122_reg_350_pp0_iter11_reg <= mul_ln122_reg_350_pp0_iter10_reg;
        mul_ln122_reg_350_pp0_iter12_reg <= mul_ln122_reg_350_pp0_iter11_reg;
        mul_ln122_reg_350_pp0_iter13_reg <= mul_ln122_reg_350_pp0_iter12_reg;
        mul_ln122_reg_350_pp0_iter14_reg <= mul_ln122_reg_350_pp0_iter13_reg;
        mul_ln122_reg_350_pp0_iter15_reg <= mul_ln122_reg_350_pp0_iter14_reg;
        mul_ln122_reg_350_pp0_iter16_reg <= mul_ln122_reg_350_pp0_iter15_reg;
        mul_ln122_reg_350_pp0_iter17_reg <= mul_ln122_reg_350_pp0_iter16_reg;
        mul_ln122_reg_350_pp0_iter18_reg <= mul_ln122_reg_350_pp0_iter17_reg;
        mul_ln122_reg_350_pp0_iter19_reg <= mul_ln122_reg_350_pp0_iter18_reg;
        mul_ln122_reg_350_pp0_iter20_reg <= mul_ln122_reg_350_pp0_iter19_reg;
        mul_ln122_reg_350_pp0_iter21_reg <= mul_ln122_reg_350_pp0_iter20_reg;
        mul_ln122_reg_350_pp0_iter22_reg <= mul_ln122_reg_350_pp0_iter21_reg;
        mul_ln122_reg_350_pp0_iter23_reg <= mul_ln122_reg_350_pp0_iter22_reg;
        mul_ln122_reg_350_pp0_iter24_reg <= mul_ln122_reg_350_pp0_iter23_reg;
        mul_ln122_reg_350_pp0_iter25_reg <= mul_ln122_reg_350_pp0_iter24_reg;
        mul_ln122_reg_350_pp0_iter26_reg <= mul_ln122_reg_350_pp0_iter25_reg;
        mul_ln122_reg_350_pp0_iter27_reg <= mul_ln122_reg_350_pp0_iter26_reg;
        mul_ln122_reg_350_pp0_iter28_reg <= mul_ln122_reg_350_pp0_iter27_reg;
        mul_ln122_reg_350_pp0_iter29_reg <= mul_ln122_reg_350_pp0_iter28_reg;
        mul_ln122_reg_350_pp0_iter30_reg <= mul_ln122_reg_350_pp0_iter29_reg;
        mul_ln122_reg_350_pp0_iter31_reg <= mul_ln122_reg_350_pp0_iter30_reg;
        mul_ln122_reg_350_pp0_iter32_reg <= mul_ln122_reg_350_pp0_iter31_reg;
        mul_ln122_reg_350_pp0_iter33_reg <= mul_ln122_reg_350_pp0_iter32_reg;
        mul_ln122_reg_350_pp0_iter34_reg <= mul_ln122_reg_350_pp0_iter33_reg;
        mul_ln122_reg_350_pp0_iter35_reg <= mul_ln122_reg_350_pp0_iter34_reg;
        mul_ln122_reg_350_pp0_iter36_reg <= mul_ln122_reg_350_pp0_iter35_reg;
        mul_ln122_reg_350_pp0_iter37_reg <= mul_ln122_reg_350_pp0_iter36_reg;
        mul_ln122_reg_350_pp0_iter38_reg <= mul_ln122_reg_350_pp0_iter37_reg;
        mul_ln122_reg_350_pp0_iter5_reg <= mul_ln122_reg_350;
        mul_ln122_reg_350_pp0_iter6_reg <= mul_ln122_reg_350_pp0_iter5_reg;
        mul_ln122_reg_350_pp0_iter7_reg <= mul_ln122_reg_350_pp0_iter6_reg;
        mul_ln122_reg_350_pp0_iter8_reg <= mul_ln122_reg_350_pp0_iter7_reg;
        mul_ln122_reg_350_pp0_iter9_reg <= mul_ln122_reg_350_pp0_iter8_reg;
        reg_103_pp0_iter10_reg <= reg_103_pp0_iter9_reg;
        reg_103_pp0_iter11_reg <= reg_103_pp0_iter10_reg;
        reg_103_pp0_iter12_reg <= reg_103_pp0_iter11_reg;
        reg_103_pp0_iter13_reg <= reg_103_pp0_iter12_reg;
        reg_103_pp0_iter14_reg <= reg_103_pp0_iter13_reg;
        reg_103_pp0_iter15_reg <= reg_103_pp0_iter14_reg;
        reg_103_pp0_iter16_reg <= reg_103_pp0_iter15_reg;
        reg_103_pp0_iter17_reg <= reg_103_pp0_iter16_reg;
        reg_103_pp0_iter18_reg <= reg_103_pp0_iter17_reg;
        reg_103_pp0_iter19_reg <= reg_103_pp0_iter18_reg;
        reg_103_pp0_iter20_reg <= reg_103_pp0_iter19_reg;
        reg_103_pp0_iter21_reg <= reg_103_pp0_iter20_reg;
        reg_103_pp0_iter22_reg <= reg_103_pp0_iter21_reg;
        reg_103_pp0_iter23_reg <= reg_103_pp0_iter22_reg;
        reg_103_pp0_iter24_reg <= reg_103_pp0_iter23_reg;
        reg_103_pp0_iter25_reg <= reg_103_pp0_iter24_reg;
        reg_103_pp0_iter26_reg <= reg_103_pp0_iter25_reg;
        reg_103_pp0_iter27_reg <= reg_103_pp0_iter26_reg;
        reg_103_pp0_iter28_reg <= reg_103_pp0_iter27_reg;
        reg_103_pp0_iter29_reg <= reg_103_pp0_iter28_reg;
        reg_103_pp0_iter30_reg <= reg_103_pp0_iter29_reg;
        reg_103_pp0_iter31_reg <= reg_103_pp0_iter30_reg;
        reg_103_pp0_iter32_reg <= reg_103_pp0_iter31_reg;
        reg_103_pp0_iter33_reg <= reg_103_pp0_iter32_reg;
        reg_103_pp0_iter34_reg <= reg_103_pp0_iter33_reg;
        reg_103_pp0_iter35_reg <= reg_103_pp0_iter34_reg;
        reg_103_pp0_iter36_reg <= reg_103_pp0_iter35_reg;
        reg_103_pp0_iter37_reg <= reg_103_pp0_iter36_reg;
        reg_103_pp0_iter38_reg <= reg_103_pp0_iter37_reg;
        reg_103_pp0_iter3_reg <= reg_103;
        reg_103_pp0_iter4_reg <= reg_103_pp0_iter3_reg;
        reg_103_pp0_iter5_reg <= reg_103_pp0_iter4_reg;
        reg_103_pp0_iter6_reg <= reg_103_pp0_iter5_reg;
        reg_103_pp0_iter7_reg <= reg_103_pp0_iter6_reg;
        reg_103_pp0_iter8_reg <= reg_103_pp0_iter7_reg;
        reg_103_pp0_iter9_reg <= reg_103_pp0_iter8_reg;
        reg_98_pp0_iter10_reg <= reg_98_pp0_iter9_reg;
        reg_98_pp0_iter11_reg <= reg_98_pp0_iter10_reg;
        reg_98_pp0_iter12_reg <= reg_98_pp0_iter11_reg;
        reg_98_pp0_iter13_reg <= reg_98_pp0_iter12_reg;
        reg_98_pp0_iter14_reg <= reg_98_pp0_iter13_reg;
        reg_98_pp0_iter15_reg <= reg_98_pp0_iter14_reg;
        reg_98_pp0_iter16_reg <= reg_98_pp0_iter15_reg;
        reg_98_pp0_iter17_reg <= reg_98_pp0_iter16_reg;
        reg_98_pp0_iter18_reg <= reg_98_pp0_iter17_reg;
        reg_98_pp0_iter19_reg <= reg_98_pp0_iter18_reg;
        reg_98_pp0_iter20_reg <= reg_98_pp0_iter19_reg;
        reg_98_pp0_iter21_reg <= reg_98_pp0_iter20_reg;
        reg_98_pp0_iter22_reg <= reg_98_pp0_iter21_reg;
        reg_98_pp0_iter23_reg <= reg_98_pp0_iter22_reg;
        reg_98_pp0_iter24_reg <= reg_98_pp0_iter23_reg;
        reg_98_pp0_iter25_reg <= reg_98_pp0_iter24_reg;
        reg_98_pp0_iter26_reg <= reg_98_pp0_iter25_reg;
        reg_98_pp0_iter27_reg <= reg_98_pp0_iter26_reg;
        reg_98_pp0_iter28_reg <= reg_98_pp0_iter27_reg;
        reg_98_pp0_iter29_reg <= reg_98_pp0_iter28_reg;
        reg_98_pp0_iter30_reg <= reg_98_pp0_iter29_reg;
        reg_98_pp0_iter31_reg <= reg_98_pp0_iter30_reg;
        reg_98_pp0_iter32_reg <= reg_98_pp0_iter31_reg;
        reg_98_pp0_iter33_reg <= reg_98_pp0_iter32_reg;
        reg_98_pp0_iter34_reg <= reg_98_pp0_iter33_reg;
        reg_98_pp0_iter35_reg <= reg_98_pp0_iter34_reg;
        reg_98_pp0_iter36_reg <= reg_98_pp0_iter35_reg;
        reg_98_pp0_iter37_reg <= reg_98_pp0_iter36_reg;
        reg_98_pp0_iter38_reg <= reg_98_pp0_iter37_reg;
        reg_98_pp0_iter3_reg <= reg_98;
        reg_98_pp0_iter4_reg <= reg_98_pp0_iter3_reg;
        reg_98_pp0_iter5_reg <= reg_98_pp0_iter4_reg;
        reg_98_pp0_iter6_reg <= reg_98_pp0_iter5_reg;
        reg_98_pp0_iter7_reg <= reg_98_pp0_iter6_reg;
        reg_98_pp0_iter8_reg <= reg_98_pp0_iter7_reg;
        reg_98_pp0_iter9_reg <= reg_98_pp0_iter8_reg;
        sdiv_ln126_reg_355 <= grp_fu_213_p2;
        select_ln106_reg_345 <= select_ln106_fu_250_p3;
        select_ln106_reg_345_pp0_iter10_reg <= select_ln106_reg_345_pp0_iter9_reg;
        select_ln106_reg_345_pp0_iter11_reg <= select_ln106_reg_345_pp0_iter10_reg;
        select_ln106_reg_345_pp0_iter12_reg <= select_ln106_reg_345_pp0_iter11_reg;
        select_ln106_reg_345_pp0_iter13_reg <= select_ln106_reg_345_pp0_iter12_reg;
        select_ln106_reg_345_pp0_iter14_reg <= select_ln106_reg_345_pp0_iter13_reg;
        select_ln106_reg_345_pp0_iter15_reg <= select_ln106_reg_345_pp0_iter14_reg;
        select_ln106_reg_345_pp0_iter16_reg <= select_ln106_reg_345_pp0_iter15_reg;
        select_ln106_reg_345_pp0_iter17_reg <= select_ln106_reg_345_pp0_iter16_reg;
        select_ln106_reg_345_pp0_iter18_reg <= select_ln106_reg_345_pp0_iter17_reg;
        select_ln106_reg_345_pp0_iter19_reg <= select_ln106_reg_345_pp0_iter18_reg;
        select_ln106_reg_345_pp0_iter20_reg <= select_ln106_reg_345_pp0_iter19_reg;
        select_ln106_reg_345_pp0_iter21_reg <= select_ln106_reg_345_pp0_iter20_reg;
        select_ln106_reg_345_pp0_iter22_reg <= select_ln106_reg_345_pp0_iter21_reg;
        select_ln106_reg_345_pp0_iter23_reg <= select_ln106_reg_345_pp0_iter22_reg;
        select_ln106_reg_345_pp0_iter24_reg <= select_ln106_reg_345_pp0_iter23_reg;
        select_ln106_reg_345_pp0_iter25_reg <= select_ln106_reg_345_pp0_iter24_reg;
        select_ln106_reg_345_pp0_iter26_reg <= select_ln106_reg_345_pp0_iter25_reg;
        select_ln106_reg_345_pp0_iter27_reg <= select_ln106_reg_345_pp0_iter26_reg;
        select_ln106_reg_345_pp0_iter28_reg <= select_ln106_reg_345_pp0_iter27_reg;
        select_ln106_reg_345_pp0_iter29_reg <= select_ln106_reg_345_pp0_iter28_reg;
        select_ln106_reg_345_pp0_iter30_reg <= select_ln106_reg_345_pp0_iter29_reg;
        select_ln106_reg_345_pp0_iter31_reg <= select_ln106_reg_345_pp0_iter30_reg;
        select_ln106_reg_345_pp0_iter32_reg <= select_ln106_reg_345_pp0_iter31_reg;
        select_ln106_reg_345_pp0_iter33_reg <= select_ln106_reg_345_pp0_iter32_reg;
        select_ln106_reg_345_pp0_iter34_reg <= select_ln106_reg_345_pp0_iter33_reg;
        select_ln106_reg_345_pp0_iter35_reg <= select_ln106_reg_345_pp0_iter34_reg;
        select_ln106_reg_345_pp0_iter36_reg <= select_ln106_reg_345_pp0_iter35_reg;
        select_ln106_reg_345_pp0_iter37_reg <= select_ln106_reg_345_pp0_iter36_reg;
        select_ln106_reg_345_pp0_iter38_reg <= select_ln106_reg_345_pp0_iter37_reg;
        select_ln106_reg_345_pp0_iter4_reg <= select_ln106_reg_345;
        select_ln106_reg_345_pp0_iter5_reg <= select_ln106_reg_345_pp0_iter4_reg;
        select_ln106_reg_345_pp0_iter6_reg <= select_ln106_reg_345_pp0_iter5_reg;
        select_ln106_reg_345_pp0_iter7_reg <= select_ln106_reg_345_pp0_iter6_reg;
        select_ln106_reg_345_pp0_iter8_reg <= select_ln106_reg_345_pp0_iter7_reg;
        select_ln106_reg_345_pp0_iter9_reg <= select_ln106_reg_345_pp0_iter8_reg;
        select_ln110_reg_340 <= select_ln110_fu_231_p3;
        select_ln110_reg_340_pp0_iter10_reg <= select_ln110_reg_340_pp0_iter9_reg;
        select_ln110_reg_340_pp0_iter11_reg <= select_ln110_reg_340_pp0_iter10_reg;
        select_ln110_reg_340_pp0_iter12_reg <= select_ln110_reg_340_pp0_iter11_reg;
        select_ln110_reg_340_pp0_iter13_reg <= select_ln110_reg_340_pp0_iter12_reg;
        select_ln110_reg_340_pp0_iter14_reg <= select_ln110_reg_340_pp0_iter13_reg;
        select_ln110_reg_340_pp0_iter15_reg <= select_ln110_reg_340_pp0_iter14_reg;
        select_ln110_reg_340_pp0_iter16_reg <= select_ln110_reg_340_pp0_iter15_reg;
        select_ln110_reg_340_pp0_iter17_reg <= select_ln110_reg_340_pp0_iter16_reg;
        select_ln110_reg_340_pp0_iter18_reg <= select_ln110_reg_340_pp0_iter17_reg;
        select_ln110_reg_340_pp0_iter19_reg <= select_ln110_reg_340_pp0_iter18_reg;
        select_ln110_reg_340_pp0_iter20_reg <= select_ln110_reg_340_pp0_iter19_reg;
        select_ln110_reg_340_pp0_iter21_reg <= select_ln110_reg_340_pp0_iter20_reg;
        select_ln110_reg_340_pp0_iter22_reg <= select_ln110_reg_340_pp0_iter21_reg;
        select_ln110_reg_340_pp0_iter23_reg <= select_ln110_reg_340_pp0_iter22_reg;
        select_ln110_reg_340_pp0_iter24_reg <= select_ln110_reg_340_pp0_iter23_reg;
        select_ln110_reg_340_pp0_iter25_reg <= select_ln110_reg_340_pp0_iter24_reg;
        select_ln110_reg_340_pp0_iter26_reg <= select_ln110_reg_340_pp0_iter25_reg;
        select_ln110_reg_340_pp0_iter27_reg <= select_ln110_reg_340_pp0_iter26_reg;
        select_ln110_reg_340_pp0_iter28_reg <= select_ln110_reg_340_pp0_iter27_reg;
        select_ln110_reg_340_pp0_iter29_reg <= select_ln110_reg_340_pp0_iter28_reg;
        select_ln110_reg_340_pp0_iter30_reg <= select_ln110_reg_340_pp0_iter29_reg;
        select_ln110_reg_340_pp0_iter31_reg <= select_ln110_reg_340_pp0_iter30_reg;
        select_ln110_reg_340_pp0_iter32_reg <= select_ln110_reg_340_pp0_iter31_reg;
        select_ln110_reg_340_pp0_iter33_reg <= select_ln110_reg_340_pp0_iter32_reg;
        select_ln110_reg_340_pp0_iter34_reg <= select_ln110_reg_340_pp0_iter33_reg;
        select_ln110_reg_340_pp0_iter35_reg <= select_ln110_reg_340_pp0_iter34_reg;
        select_ln110_reg_340_pp0_iter36_reg <= select_ln110_reg_340_pp0_iter35_reg;
        select_ln110_reg_340_pp0_iter37_reg <= select_ln110_reg_340_pp0_iter36_reg;
        select_ln110_reg_340_pp0_iter38_reg <= select_ln110_reg_340_pp0_iter37_reg;
        select_ln110_reg_340_pp0_iter4_reg <= select_ln110_reg_340;
        select_ln110_reg_340_pp0_iter5_reg <= select_ln110_reg_340_pp0_iter4_reg;
        select_ln110_reg_340_pp0_iter6_reg <= select_ln110_reg_340_pp0_iter5_reg;
        select_ln110_reg_340_pp0_iter7_reg <= select_ln110_reg_340_pp0_iter6_reg;
        select_ln110_reg_340_pp0_iter8_reg <= select_ln110_reg_340_pp0_iter7_reg;
        select_ln110_reg_340_pp0_iter9_reg <= select_ln110_reg_340_pp0_iter8_reg;
        sub_ln118_reg_300 <= sub_ln118_fu_133_p2;
        sub_ln118_reg_300_pp0_iter10_reg <= sub_ln118_reg_300_pp0_iter9_reg;
        sub_ln118_reg_300_pp0_iter11_reg <= sub_ln118_reg_300_pp0_iter10_reg;
        sub_ln118_reg_300_pp0_iter12_reg <= sub_ln118_reg_300_pp0_iter11_reg;
        sub_ln118_reg_300_pp0_iter13_reg <= sub_ln118_reg_300_pp0_iter12_reg;
        sub_ln118_reg_300_pp0_iter14_reg <= sub_ln118_reg_300_pp0_iter13_reg;
        sub_ln118_reg_300_pp0_iter15_reg <= sub_ln118_reg_300_pp0_iter14_reg;
        sub_ln118_reg_300_pp0_iter16_reg <= sub_ln118_reg_300_pp0_iter15_reg;
        sub_ln118_reg_300_pp0_iter17_reg <= sub_ln118_reg_300_pp0_iter16_reg;
        sub_ln118_reg_300_pp0_iter18_reg <= sub_ln118_reg_300_pp0_iter17_reg;
        sub_ln118_reg_300_pp0_iter19_reg <= sub_ln118_reg_300_pp0_iter18_reg;
        sub_ln118_reg_300_pp0_iter20_reg <= sub_ln118_reg_300_pp0_iter19_reg;
        sub_ln118_reg_300_pp0_iter21_reg <= sub_ln118_reg_300_pp0_iter20_reg;
        sub_ln118_reg_300_pp0_iter22_reg <= sub_ln118_reg_300_pp0_iter21_reg;
        sub_ln118_reg_300_pp0_iter23_reg <= sub_ln118_reg_300_pp0_iter22_reg;
        sub_ln118_reg_300_pp0_iter24_reg <= sub_ln118_reg_300_pp0_iter23_reg;
        sub_ln118_reg_300_pp0_iter25_reg <= sub_ln118_reg_300_pp0_iter24_reg;
        sub_ln118_reg_300_pp0_iter26_reg <= sub_ln118_reg_300_pp0_iter25_reg;
        sub_ln118_reg_300_pp0_iter27_reg <= sub_ln118_reg_300_pp0_iter26_reg;
        sub_ln118_reg_300_pp0_iter28_reg <= sub_ln118_reg_300_pp0_iter27_reg;
        sub_ln118_reg_300_pp0_iter29_reg <= sub_ln118_reg_300_pp0_iter28_reg;
        sub_ln118_reg_300_pp0_iter30_reg <= sub_ln118_reg_300_pp0_iter29_reg;
        sub_ln118_reg_300_pp0_iter31_reg <= sub_ln118_reg_300_pp0_iter30_reg;
        sub_ln118_reg_300_pp0_iter32_reg <= sub_ln118_reg_300_pp0_iter31_reg;
        sub_ln118_reg_300_pp0_iter33_reg <= sub_ln118_reg_300_pp0_iter32_reg;
        sub_ln118_reg_300_pp0_iter34_reg <= sub_ln118_reg_300_pp0_iter33_reg;
        sub_ln118_reg_300_pp0_iter35_reg <= sub_ln118_reg_300_pp0_iter34_reg;
        sub_ln118_reg_300_pp0_iter36_reg <= sub_ln118_reg_300_pp0_iter35_reg;
        sub_ln118_reg_300_pp0_iter37_reg <= sub_ln118_reg_300_pp0_iter36_reg;
        sub_ln118_reg_300_pp0_iter38_reg <= sub_ln118_reg_300_pp0_iter37_reg;
        sub_ln118_reg_300_pp0_iter3_reg <= sub_ln118_reg_300;
        sub_ln118_reg_300_pp0_iter4_reg <= sub_ln118_reg_300_pp0_iter3_reg;
        sub_ln118_reg_300_pp0_iter5_reg <= sub_ln118_reg_300_pp0_iter4_reg;
        sub_ln118_reg_300_pp0_iter6_reg <= sub_ln118_reg_300_pp0_iter5_reg;
        sub_ln118_reg_300_pp0_iter7_reg <= sub_ln118_reg_300_pp0_iter6_reg;
        sub_ln118_reg_300_pp0_iter8_reg <= sub_ln118_reg_300_pp0_iter7_reg;
        sub_ln118_reg_300_pp0_iter9_reg <= sub_ln118_reg_300_pp0_iter8_reg;
        tmp_1_reg_310 <= data_b_dout[32'd31];
        tmp_reg_325 <= data_a_dout[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd1 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd3 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd8 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd9 == ALU_operation_read_reg_296)))) begin
        reg_103 <= data_b_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd0 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd2 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd8 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd9 == ALU_operation_read_reg_296)))) begin
        reg_98 <= data_a_dout;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ALU_operation_blk_n = ALU_operation_empty_n;
    end else begin
        ALU_operation_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ALU_operation_read = 1'b1;
    end else begin
        ALU_operation_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_116_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter38_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) 
    & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_64;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd0 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd2 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd4 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd6 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd7 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd8 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd9 == ALU_operation_read_reg_296)))) begin
        data_a_blk_n = data_a_empty_n;
    end else begin
        data_a_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd0 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd2 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd4 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd6 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd7 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd8 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd9 == ALU_operation_read_reg_296)))) begin
        data_a_read = 1'b1;
    end else begin
        data_a_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd1 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd3 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd5 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd6 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd7 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd8 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd9 == ALU_operation_read_reg_296)))) begin
        data_b_blk_n = data_b_empty_n;
    end else begin
        data_b_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd1 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd3 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd5 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd6 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd7 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd8 == ALU_operation_read_reg_296)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (32'd9 == ALU_operation_read_reg_296)))) begin
        data_b_read = 1'b1;
    end else begin
        data_b_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred372_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred367_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred362_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred357_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred352_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred347_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred342_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred337_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred332_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred325_state40 
    == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op155_write_state40 == 1'b1) & (ap_enable_reg_pp0_iter39 == 1'b1)))) begin
        data_result_blk_n = data_result_full_n;
    end else begin
        data_result_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
        if ((ap_predicate_op155_write_state40 == 1'b1)) begin
            data_result_din = 32'd0;
        end else if ((ap_predicate_pred325_state40 == 1'b1)) begin
            data_result_din = add_ln90_fu_278_p2;
        end else if ((ap_predicate_pred332_state40 == 1'b1)) begin
            data_result_din = add_ln94_fu_271_p2;
        end else if ((ap_predicate_pred337_state40 == 1'b1)) begin
            data_result_din = shl_ln98_fu_264_p2;
        end else if ((ap_predicate_pred342_state40 == 1'b1)) begin
            data_result_din = shl_ln102_fu_257_p2;
        end else if ((ap_predicate_pred347_state40 == 1'b1)) begin
            data_result_din = select_ln106_reg_345_pp0_iter38_reg;
        end else if ((ap_predicate_pred352_state40 == 1'b1)) begin
            data_result_din = select_ln110_reg_340_pp0_iter38_reg;
        end else if ((ap_predicate_pred357_state40 == 1'b1)) begin
            data_result_din = add_ln114_reg_305_pp0_iter38_reg;
        end else if ((ap_predicate_pred362_state40 == 1'b1)) begin
            data_result_din = sub_ln118_reg_300_pp0_iter38_reg;
        end else if ((ap_predicate_pred367_state40 == 1'b1)) begin
            data_result_din = mul_ln122_reg_350_pp0_iter38_reg;
        end else if ((ap_predicate_pred372_state40 == 1'b1)) begin
            data_result_din = sdiv_ln126_reg_355;
        end else begin
            data_result_din = 'bx;
        end
    end else begin
        data_result_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred372_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred367_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred362_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred357_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred352_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred347_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred342_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred337_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred332_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & 
    (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_predicate_pred325_state40 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op155_write_state40 == 1'b1) & (ap_enable_reg_pp0_iter39 == 1'b1)))) begin
        data_result_write = 1'b1;
    end else begin
        data_result_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_213_ce = 1'b1;
    end else begin
        grp_fu_213_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_94_ce = 1'b1;
    end else begin
        grp_fu_94_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln114_fu_139_p2 = (data_b_dout + data_a_dout);

assign add_ln90_fu_278_p2 = (reg_98_pp0_iter38_reg + 32'd27);

assign add_ln94_fu_271_p2 = (reg_103_pp0_iter38_reg + 32'd27);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b1 == ap_block_state40_pp0_stage0_iter39) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state40_pp0_stage0_iter39) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state40_pp0_stage0_iter39) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (1'b0 == ALU_operation_empty_n);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((32'd1 == ALU_operation_read_reg_296) & (data_b_empty_n == 1'b0)) | ((32'd2 == ALU_operation_read_reg_296) & (data_a_empty_n == 1'b0)) | ((32'd3 == ALU_operation_read_reg_296) & (data_b_empty_n == 1'b0)) | ((32'd4 == ALU_operation_read_reg_296) & (data_a_empty_n == 1'b0)) | ((32'd5 == ALU_operation_read_reg_296) & (data_b_empty_n == 1'b0)) | ((32'd6 == ALU_operation_read_reg_296) & (data_b_empty_n == 1'b0)) | ((32'd6 == ALU_operation_read_reg_296) & (data_a_empty_n == 1'b0)) | ((32'd7 == ALU_operation_read_reg_296) & (data_b_empty_n == 1'b0)) | ((32'd7 == ALU_operation_read_reg_296) & (data_a_empty_n == 1'b0)) | ((32'd8 == ALU_operation_read_reg_296) & (data_b_empty_n == 1'b0)) | ((32'd8 == ALU_operation_read_reg_296) & (data_a_empty_n == 1'b0)) | ((data_b_empty_n == 1'b0) & (32'd9 == ALU_operation_read_reg_296)) | ((32'd9 == ALU_operation_read_reg_296) & (data_a_empty_n == 1'b0)) | ((data_a_empty_n == 1'b0) & (32'd0 == ALU_operation_read_reg_296)));
end

always @ (*) begin
    ap_block_state40_pp0_stage0_iter39 = (((ap_predicate_op155_write_state40 == 1'b1) & (data_result_full_n == 1'b0)) | ((data_result_full_n == 1'b0) & (32'd0 == ALU_operation_read_reg_296_pp0_iter38_reg)) | ((data_result_full_n == 1'b0) & (32'd1 == ALU_operation_read_reg_296_pp0_iter38_reg)) | ((data_result_full_n == 1'b0) & (32'd2 == ALU_operation_read_reg_296_pp0_iter38_reg)) | ((data_result_full_n == 1'b0) & (32'd3 == ALU_operation_read_reg_296_pp0_iter38_reg)) | ((data_result_full_n == 1'b0) & (32'd4 == ALU_operation_read_reg_296_pp0_iter38_reg)) | ((data_result_full_n == 1'b0) & (32'd5 == ALU_operation_read_reg_296_pp0_iter38_reg)) | ((data_result_full_n == 1'b0) & (32'd6 == ALU_operation_read_reg_296_pp0_iter38_reg)) | ((data_result_full_n == 1'b0) & (32'd7 == ALU_operation_read_reg_296_pp0_iter38_reg)) | ((data_result_full_n == 1'b0) & (32'd8 == ALU_operation_read_reg_296_pp0_iter38_reg)) | ((data_result_full_n == 1'b0) & (32'd9 == ALU_operation_read_reg_296_pp0_iter38_reg)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op155_write_state40 = (~(32'd0 == ALU_operation_read_reg_296_pp0_iter38_reg) & ~(32'd1 == ALU_operation_read_reg_296_pp0_iter38_reg) & ~(32'd2 == ALU_operation_read_reg_296_pp0_iter38_reg) & ~(32'd3 == ALU_operation_read_reg_296_pp0_iter38_reg) & ~(32'd4 == ALU_operation_read_reg_296_pp0_iter38_reg) & ~(32'd5 == ALU_operation_read_reg_296_pp0_iter38_reg) & ~(32'd6 == ALU_operation_read_reg_296_pp0_iter38_reg) & ~(32'd7 == ALU_operation_read_reg_296_pp0_iter38_reg) & ~(32'd8 == ALU_operation_read_reg_296_pp0_iter38_reg) & ~(32'd9 == ALU_operation_read_reg_296_pp0_iter38_reg));
end

assign i_2_fu_122_p2 = (ap_sig_allocacmp_i_1 + 6'd1);

assign icmp_ln82_fu_116_p2 = ((ap_sig_allocacmp_i_1 == 6'd50) ? 1'b1 : 1'b0);

assign select_ln106_fu_250_p3 = ((tmp_reg_325[0:0] == 1'b1) ? sub_ln106_1_fu_241_p2 : zext_ln106_1_fu_247_p1);

assign select_ln110_fu_231_p3 = ((tmp_1_reg_310[0:0] == 1'b1) ? sub_ln110_1_fu_222_p2 : zext_ln110_1_fu_228_p1);

assign shl_ln102_fu_257_p2 = reg_103_pp0_iter38_reg << 32'd1;

assign shl_ln98_fu_264_p2 = reg_98_pp0_iter38_reg << 32'd1;

assign sub_ln106_1_fu_241_p2 = (32'd0 - zext_ln106_fu_238_p1);

assign sub_ln106_fu_187_p2 = (32'd0 - data_a_dout);

assign sub_ln110_1_fu_222_p2 = (32'd0 - zext_ln110_fu_219_p1);

assign sub_ln110_fu_153_p2 = (32'd0 - data_b_dout);

assign sub_ln118_fu_133_p2 = (data_a_dout - data_b_dout);

assign zext_ln106_1_fu_247_p1 = lshr_ln106_2_reg_335;

assign zext_ln106_fu_238_p1 = lshr_ln106_1_reg_330;

assign zext_ln110_1_fu_228_p1 = lshr_ln110_2_reg_320;

assign zext_ln110_fu_219_p1 = lshr_ln110_1_reg_315;

endmodule //alv_MIMD_execute
