# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SISD_block_design/SISD_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SISD_block_design || ORIG_REF_NAME==SISD_block_design} -quiet] -quiet

# IP: bd/SISD_block_design/ip/SISD_block_design_processing_system7_0_0/SISD_block_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SISD_block_design_processing_system7_0_0 || ORIG_REF_NAME==SISD_block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/SISD_block_design/ip/SISD_block_design_sisd_0_0/SISD_block_design_sisd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SISD_block_design_sisd_0_0 || ORIG_REF_NAME==SISD_block_design_sisd_0_0} -quiet] -quiet

# IP: bd/SISD_block_design/ip/SISD_block_design_auto_pc_0/SISD_block_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SISD_block_design_auto_pc_0 || ORIG_REF_NAME==SISD_block_design_auto_pc_0} -quiet] -quiet

# IP: bd/SISD_block_design/ip/SISD_block_design_ps7_0_axi_periph_0/SISD_block_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SISD_block_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==SISD_block_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/SISD_block_design/ip/SISD_block_design_rst_ps7_0_50M_0/SISD_block_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SISD_block_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==SISD_block_design_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Users/lotto/Desktop/Alveare/SISD/SISD/SISD.gen/sources_1/bd/SISD_block_design/SISD_block_design_ooc.xdc
